#!/usr/bin/env bash
# Builds the aquarevwater.us deliverables for the two Certification pages from the two master
# files in Marketing/Collateral/Certification. Re-run after any change to the masters, then push.
#
#   Page 1: /certificationmap  (interactive atlas)
#     certification-map.css / certification-map.js / webflow-embed-certification-map.html / preview.html
#   Page 2: /compliancemap     (the full Global Compliance Map document)
#     compliance-map.css / compliance-map.js / webflow-embed-compliance-map.html / preview-doc.html
#
# Each JS file injects its page markup into an empty container (#arcm or #arcd) and every style is
# scoped under that container, so Webflow's global styles never reach the page and vice versa.
set -euo pipefail

HERE="$(cd "$(dirname "$0")" && pwd)"
MASTER="/Users/jatley/Documents/Jeff Atley/Aquarev Water /Marketing/Collateral/Certification"
ATLAS="$MASTER/AquaRev_Compliance_Atlas_V1.html"
DOC="$MASTER/AquaRev_Global_Compliance_Map_V1.html"
PAGES="https://jeffatley-web.github.io/aquarev_certification_map"
SITE_MAP="https://www.aquarevwater.us/certificationmap"
SITE_DOC="https://www.aquarevwater.us/compliancemap"
ARTIFACT_DOC="https://claude.ai/artifact/5e3h82FST3RaScjGqJqVT9"
ARTIFACT_ATLAS="https://claude.ai/artifact/MJug8Z6Be3f7m8a4jhPTup"
STAMP="$(date +%Y%m%d%H%M)"
FONTS='https://fonts.googleapis.com/css2?family=Archivo:wdth,wght@75..100,400..700&family=Source+Sans+3:ital,wght@0,400;0,600;1,400&family=IBM+Plex+Mono:wght@400;500&display=swap'

cd "$HERE"

# scope_css ROOT STICKYVAR  — reads CSS on stdin, writes CSS scoped under #ROOT on stdout
scope_css() {
  local root="$1" sticky="$2"
  sed -E \
    -e 's#/\*[^*]*\*/##g' \
    -e "s/^:root\{/#${root}{/" \
    -e "s/:root:not\(\[data-theme=\"light\"\]\)\{/#${root}{/" \
    -e "s/^:root\[data-theme=\"dark\"\]\{/#${root}[data-theme=\"dark\"]{/" \
    -e '/^html\{scroll-behavior:smooth\}$/d' \
    -e '/^@media \(prefers-reduced-motion:reduce\)\{html\{scroll-behavior:auto\}\}$/d' \
    -e "s/^body\{/#${root}{/" \
    -e "s/position:sticky;top:0;z-index:5;/position:sticky;top:var(--${sticky},0px);z-index:5;/" \
  | perl -e '
    my $css = do { local $/; <STDIN> }; my $root = shift @ARGV; my $out = "";
    while ($css =~ /\G([^{}]*)([{}])/gc) {
      my ($txt, $br) = ($1, $2);
      if ($br eq "{") {
        if ($txt =~ /^\s*@/) { $out .= $txt . "{"; }
        else {
          my ($lead) = $txt =~ /^(\s*)/;
          my @parts = map { my $s = $_; $s =~ s/^\s+|\s+$//g; ($s =~ /^#$root/ ? $s : "#$root $s") } split /,/, $txt;
          $out .= $lead . join(", ", @parts) . "{";
        }
      } else { $out .= $txt . "}"; }
    }
    $out .= substr($css, pos($css) // 0); print $out;
  ' "$root"
}

# nav_offset_js VARNAME — emits JS that measures the site's sticky/fixed nav and sets --VARNAME on the
# container to its height, so the page's sticky bars and the record drawer sit below the nav.
nav_offset_js() {
  cat <<EOF
(function(){
  function navOffset(){
    var nav=document.querySelector('.w-nav, nav'); var h=0;
    if(nav){ var cs=getComputedStyle(nav); if(cs.position==='sticky'||cs.position==='fixed'){ h=Math.round(nav.getBoundingClientRect().height); } }
    root.style.setProperty('--$1', h+'px');
  }
  navOffset(); window.addEventListener('resize', navOffset); window.addEventListener('load', navOffset);
})();
EOF
}

# ================= Page 1: atlas =================
{
  echo "/* AquaRev Certification Map (atlas). Generated by build.sh from the atlas master; do not edit by hand. */"
  awk '/^<style>$/{f=1;next} /^<\/style>$/{f=0} f' "$ATLAS" | scope_css arcm arcm-sticky-top
} > certification-map.css

{
  echo "/* AquaRev Certification Map (atlas). Generated by build.sh from the atlas master; do not edit by hand. */"
  echo "(function(){"
  echo "var root=document.getElementById('arcm'); if(!root) return;"
  echo "root.innerHTML=\`"
  awk '/^<div class="wrap">$/{f=1} f&&/^<script>$/{exit} f{print}' "$ATLAS" \
    | sed -E -e "s|$ARTIFACT_DOC|$SITE_DOC|g" -e 's/`/\\`/g'
  echo "\`;"
  nav_offset_js arcm-sticky-top
  awk '/^<script>$/{f=1;next} /^<\/script>$/{f=0} f' "$ATLAS" \
    | sed -E -e "s|$ARTIFACT_DOC|$SITE_DOC|g" \
             -e "s|getComputedStyle\(document\.documentElement\)|getComputedStyle(document.getElementById('arcm'))|g"
  echo "})();"
} > certification-map.js

cat > webflow-embed-certification-map.html <<EOF
<!-- AquaRev Certification Map (interactive atlas). Paste this whole block into a Webflow Embed element on /certificationmap.
     CSS and JS are hosted on GitHub Pages; bump the ?v= values after pushing changes. -->
<link rel="stylesheet" href="$FONTS">
<link rel="stylesheet" href="$PAGES/certification-map.css?v=$STAMP">
<div id="arcm" data-theme="dark"></div>
<script defer src="https://cdnjs.cloudflare.com/ajax/libs/d3/3.5.17/d3.min.js"></script>
<script defer src="https://cdnjs.cloudflare.com/ajax/libs/topojson/1.6.9/topojson.min.js"></script>
<script defer src="https://cdnjs.cloudflare.com/ajax/libs/datamaps/0.5.9/datamaps.all.min.js"></script>
<script defer src="$PAGES/certification-map.js?v=$STAMP"></script>
EOF

cat > preview.html <<EOF
<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width,initial-scale=1">
<title>Preview: AquaRev Certification Map (local, mirrors the Webflow embed)</title>
<style>body{margin:0;background:#0E171E;font-family:sans-serif}</style>
</head>
<body>
<link rel="stylesheet" href="$FONTS">
<link rel="stylesheet" href="certification-map.css">
<div id="arcm" data-theme="dark"></div>
<script defer src="https://cdnjs.cloudflare.com/ajax/libs/d3/3.5.17/d3.min.js"></script>
<script defer src="https://cdnjs.cloudflare.com/ajax/libs/topojson/1.6.9/topojson.min.js"></script>
<script defer src="https://cdnjs.cloudflare.com/ajax/libs/datamaps/0.5.9/datamaps.all.min.js"></script>
<script defer src="certification-map.js"></script>
</body>
</html>
EOF

# ================= Page 2: document =================
{
  echo "/* AquaRev Global Compliance Map (document). Generated by build.sh from the document master; do not edit by hand. */"
  awk '/^<style>$/{f=1;next} /^<\/style>$/{f=0} f' "$DOC" | scope_css arcd arcd-sticky-top
} > compliance-map.css

{
  echo "/* AquaRev Global Compliance Map (document). Generated by build.sh from the document master; do not edit by hand. */"
  echo "(function(){"
  echo "var root=document.getElementById('arcd'); if(!root) return;"
  echo "root.innerHTML=\`"
  awk '/^<div class="wrap">$/{f=1} f&&/^<script>$/{exit} f{print}' "$DOC" \
    | sed -E -e "s|$ARTIFACT_ATLAS|$SITE_MAP|g" -e 's/`/\\`/g'
  echo "\`;"
  nav_offset_js arcd-sticky-top
  awk '/^<script>$/{f=1;next} /^<\/script>$/{f=0} f' "$DOC"
  # Deep links from the atlas arrive as #anchors; scroll to them once the markup exists.
  echo "if(location.hash){ var t=document.getElementById(decodeURIComponent(location.hash.slice(1))); if(t){ setTimeout(function(){ t.scrollIntoView({block:'start'}); }, 80); } }"
  echo "window.addEventListener('hashchange',function(){ var t=document.getElementById(decodeURIComponent(location.hash.slice(1))); if(t) t.scrollIntoView({block:'start'}); });"
  echo "})();"
} > compliance-map.js

cat > webflow-embed-compliance-map.html <<EOF
<!-- AquaRev Global Compliance Map (document). Paste this whole block into a Webflow Embed element on /compliancemap.
     CSS and JS are hosted on GitHub Pages; bump the ?v= values after pushing changes. -->
<link rel="stylesheet" href="$FONTS">
<link rel="stylesheet" href="$PAGES/compliance-map.css?v=$STAMP">
<div id="arcd" data-theme="dark"></div>
<script defer src="$PAGES/compliance-map.js?v=$STAMP"></script>
EOF

cat > preview-doc.html <<EOF
<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width,initial-scale=1">
<title>Preview: AquaRev Global Compliance Map (local, mirrors the Webflow embed)</title>
<style>body{margin:0;background:#0E171E;font-family:sans-serif}</style>
</head>
<body>
<link rel="stylesheet" href="$FONTS">
<link rel="stylesheet" href="compliance-map.css">
<div id="arcd" data-theme="dark"></div>
<script defer src="compliance-map.js"></script>
</body>
</html>
EOF

rm -f compliance-map.html
wc -c certification-map.css certification-map.js compliance-map.css compliance-map.js webflow-embed-certification-map.html webflow-embed-compliance-map.html
