#!/usr/bin/env bash
# Builds the aquarevwater.us/certificationmap deliverables from the two master files in
# Marketing/Collateral/Certification. Re-run after any change to the masters, then push.
#
#   certification-map.css      scoped copy of the atlas styles (everything under #arcm)
#   certification-map.js       atlas markup + data + logic, self-injecting into <div id="arcm">
#   compliance-map.html        the full Global Compliance Map document as a standalone page
#   preview.html               local preview that mirrors the Webflow embed
#   webflow-embed-certification-map.html   the snippet pasted into Webflow (never changes unless URLs move)
set -euo pipefail

HERE="$(cd "$(dirname "$0")" && pwd)"
MASTER="/Users/jatley/Documents/Jeff Atley/Aquarev Water /Marketing/Collateral/Certification"
ATLAS="$MASTER/AquaRev_Compliance_Atlas_V1.html"
DOC="$MASTER/AquaRev_Global_Compliance_Map_V1.html"
PAGES="https://jeffatley-web.github.io/aquarev_certification_map"
DOC_URL="$PAGES/compliance-map.html"
ARTIFACT_DOC="https://claude.ai/artifact/5e3h82FST3RaScjGqJqVT9"
STAMP="$(date +%Y%m%d)a"

cd "$HERE"

# ---------- CSS: extract the inline <style> block and scope every selector under #arcm ----------
awk '/^<style>$/{f=1;next} /^<\/style>$/{f=0} f' "$ATLAS" \
| sed -E \
    -e 's#/\*[^*]*\*/##g' \
    -e 's/^:root\{/#arcm{/' \
    -e 's/:root:not\(\[data-theme="light"\]\)\{/#arcm{/' \
    -e 's/^:root\[data-theme="dark"\]\{/#arcm[data-theme="dark"]{/' \
    -e '/^html\{scroll-behavior:smooth\}$/d' \
    -e '/^@media \(prefers-reduced-motion:reduce\)\{html\{scroll-behavior:auto\}\}$/d' \
    -e 's/^body\{/#arcm{/' \
    -e 's/position:sticky;top:0;background:var\(--ground\);z-index:6/position:sticky;top:var(--arcm-sticky-top,0px);background:var(--ground);z-index:6/' \
    -e 's/position:sticky;top:86px;max-height:calc\(100vh - 100px\)/position:sticky;top:calc(var(--arcm-sticky-top,0px) + 86px);max-height:calc(100vh - 100px - var(--arcm-sticky-top,0px))/' \
| perl -e '
  my $css = do { local $/; <STDIN> };
  my $out = "";
  while ($css =~ /\G([^{}]*)([{}])/gc) {
    my ($txt, $br) = ($1, $2);
    if ($br eq "{") {
      if ($txt =~ /^\s*@/) { $out .= $txt . "{"; }
      else {
        my ($lead) = $txt =~ /^(\s*)/;
        my @parts = map { my $s = $_; $s =~ s/^\s+|\s+$//g; ($s =~ /^#arcm/ ? $s : "#arcm $s") } split /,/, $txt;
        $out .= $lead . join(", ", @parts) . "{";
      }
    } else { $out .= $txt . "}"; }
  }
  $out .= substr($css, pos($css) // 0);
  print "/* AquaRev Certification Map. Generated by build.sh from the atlas master; do not edit by hand. */\n";
  print $out;
' > certification-map.css

# ---------- JS: markup template + logic, self-injecting ----------
{
  echo "/* AquaRev Certification Map. Generated by build.sh from the atlas master; do not edit by hand. */"
  echo "(function(){"
  echo "var root=document.getElementById('arcm'); if(!root) return;"
  echo "root.innerHTML=\`"
  awk '/^<div class="wrap">$/{f=1} f&&/^<script>$/{exit} f{print}' "$ATLAS" \
    | sed -E \
        -e "s|$ARTIFACT_DOC|$DOC_URL|g" \
        -e 's|<span>Research/ folder holds source reports</span>||' \
        -e 's/`/\\`/g'
  echo "\`;"
  awk '/^<script>$/{f=1;next} /^<\/script>$/{f=0} f' "$ATLAS" \
    | sed -E \
        -e "s|$ARTIFACT_DOC|$DOC_URL|g" \
        -e "s|getComputedStyle\(document\.documentElement\)|getComputedStyle(document.getElementById('arcm'))|g"
  echo "})();"
} > certification-map.js

# ---------- Standalone document page ----------
{
  printf '<!DOCTYPE html>\n<html lang="en" data-theme="dark">\n<head>\n'
  cat "$DOC"
  printf '\n</html>\n'
} > compliance-map.html

# ---------- Embed snippet and local preview ----------
FONTS='https://fonts.googleapis.com/css2?family=Archivo:wdth,wght@75..100,400..700&family=Source+Sans+3:wght@400;600&family=IBM+Plex+Mono:wght@400;500&display=swap'
cat > webflow-embed-certification-map.html <<EOF
<!-- AquaRev Certification Map. Paste this whole block into a Webflow Embed element on /certificationmap.
     CSS and JS are hosted on GitHub Pages; bump the ?v= values after pushing changes. -->
<link rel="stylesheet" href="$FONTS">
<link rel="stylesheet" href="$PAGES/certification-map.css?v=$STAMP">
<div id="arcm" data-theme="dark"></div>
<script defer src="https://cdnjs.cloudflare.com/ajax/libs/d3/3.5.17/d3.min.js"></script>
<script defer src="https://cdnjs.cloudflare.com/ajax/libs/topojson/1.6.9/topojson.min.js"></script>
<script defer src="https://cdnjs.cloudflare.com/ajax/libs/datamaps/0.5.9/datamaps.all.min.js"></script>
<script defer src="$PAGES/certification-map.js?v=$STAMP"></script>
EOF

cat > preview.html <<EOF
<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width,initial-scale=1">
<title>Preview: AquaRev Certification Map (local, mirrors the Webflow embed)</title>
<style>body{margin:0;background:#0E171E;font-family:sans-serif}</style>
</head>
<body>
<!-- Same block as webflow-embed-certification-map.html with the two hosted files swapped for local copies. -->
<link rel="stylesheet" href="$FONTS">
<link rel="stylesheet" href="certification-map.css">
<div id="arcm" data-theme="dark"></div>
<script defer src="https://cdnjs.cloudflare.com/ajax/libs/d3/3.5.17/d3.min.js"></script>
<script defer src="https://cdnjs.cloudflare.com/ajax/libs/topojson/1.6.9/topojson.min.js"></script>
<script defer src="https://cdnjs.cloudflare.com/ajax/libs/datamaps/0.5.9/datamaps.all.min.js"></script>
<script defer src="certification-map.js"></script>
</body>
</html>
EOF

wc -c certification-map.css certification-map.js compliance-map.html webflow-embed-certification-map.html preview.html
