/* AquaRev Certification Map (atlas). Generated by build.sh from the atlas master; do not edit by hand. */
(function(){
var root=document.getElementById('arcm'); if(!root) return;
root.innerHTML=`
<div class="wrap">
<header class="mast">
  <div>
    <div class="eyebrow">AquaRev Water · Interactive atlas · September 2026</div>
    <h1>AquaRev Compliance Atlas</h1>
    <p class="lede">Sixty jurisdictions and every US state, one device. Choose a question, then click any country, marker or state to open its record.</p>
  </div>
  <a class="doc" href="https://www.aquarevwater.us/compliancemap">Full compliance map (document) →</a>
</header>

<nav class="qtabs" id="qtabs" role="tablist" aria-label="Question">
  <button class="qtab" role="tab" data-view="gate" aria-selected="true"><span class="l">Permission to install</span><span class="d">Who must sign before the cut-in?</span></button>
  <button class="qtab" role="tab" data-view="cert" aria-selected="false"><span class="l">Product certification</span><span class="d">Is NSF/ANSI 50 required by law?</span></button>
  <button class="qtab" role="tab" data-view="process" aria-selected="false"><span class="l">Process rules</span><span class="d">Does the law restrict treatment methods?</span></button>
  <button class="qtab" role="tab" data-view="fc" aria-selected="false"><span class="l">Chlorine floor</span><span class="d">What residual must the pool still hold?</span></button>
  <button class="qtab" role="tab" data-view="conf" aria-selected="false"><span class="l">Evidence</span><span class="d">How solid is each finding?</span></button>
</nav>

<div class="controls" id="controls">
  <div class="mapbar">
    <div class="seg" role="group" aria-label="Map level"><button type="button" data-level="world" aria-pressed="true">World</button><button type="button" data-level="usa" aria-pressed="false">US states</button><button type="button" data-level="list" aria-pressed="false">Table</button></div>
    <label class="focus" id="focuswrap"><span class="lab">Focus</span><span class="sel"><select id="focus" aria-label="Region focus"><option value="world">Whole world</option><option value="na">North America</option><option value="carib">Caribbean</option><option value="eu">Europe</option><option value="me">Middle East</option><option value="af">Africa</option><option value="apac">Asia-Pacific</option><option value="latam">Latin America</option></select></span></label>
    <div class="grow"></div>
    <div class="search">
      <svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" aria-hidden="true"><circle cx="11" cy="11" r="7"></circle><path d="m20 20-3.5-3.5"></path></svg>
      <input type="search" id="q" placeholder="Find a country, state or agency" aria-label="Find a jurisdiction" autocomplete="off" role="combobox" aria-expanded="false" aria-controls="results">
      <div class="results" id="results" role="listbox"></div>
    </div>
    <button class="help-btn" id="helpbtn" type="button" aria-expanded="false" aria-controls="help" title="How to use this atlas">?</button>
  </div>
  <div class="help" id="help" role="dialog" aria-label="How to use this atlas" hidden>
    <h3>How to use this atlas</h3>
    <p>Choose a question in the strip above; the map recolours to answer it. Click any coloured country or marker to open its record. Click a legend entry or a tile to isolate one answer. Hover for a summary. Scroll or drag on the map to zoom and pan.</p>
    <ul>
      <li><b>Permission to install</b> is the one that costs time: red means someone must sign before the cut-in.</li>
      <li><b>Product certification</b> is required by law only in North America; the IAPMO certificate already satisfies it.</li>
      <li><b>Process rules</b> are where a wrong word on the spec sheet creates a problem.</li>
      <li><b>Chlorine floor</b> is the residual the 41% claim must never touch.</li>
      <li><b>Evidence</b> grades each record: primary text read, reputable summary, or reasoned from the framework.</li>
    </ul>
    <div class="foot">Sixty jurisdictions plus all 50 US states and DC, researched September 2026. Grey land is not yet researched. Not legal advice.</div>
  </div>
</div>
<section class="mapcard" id="mapcard">
  <div class="maptitle"><h2 id="maptitle">Permission to install: what must happen before the device goes in</h2><span class="hint" id="hint">Hover for a summary · click to open the record · scroll or drag to zoom and pan</span></div>
  <div class="mapwrap">
    <div id="map"></div>
    <div class="mapctl"><button id="zin" type="button" title="Zoom in" aria-label="Zoom in">+</button><button id="zout" type="button" title="Zoom out" aria-label="Zoom out">−</button><button id="zreset" type="button" title="Reset view" aria-label="Reset view">⌂</button></div>
  </div>
</section>
<section class="listcard hidden" id="listcard">
  <div class="maptitle"><h2 id="listtitle">Permission to install: what must happen before the device goes in</h2><span class="hint" id="listhint">Click a column heading to sort · click a name to open the record</span><span class="count" id="listcount"></span></div>
  <div class="tablewrap"><table id="tbl"><thead><tr><th data-s="name">Jurisdiction</th><th data-s="region">Region</th><th data-s="gate">Permission to install</th><th data-s="cert">Product certification</th><th data-s="process">Process</th><th data-s="trig">Conditional trigger</th><th data-s="fcMin">FC min</th><th data-s="ph">pH</th><th data-s="conf">Evidence</th></tr></thead><tbody></tbody></table></div>
</section>
<div class="legend" id="legend"></div>
<div class="stats" id="stats"></div>
<p class="note">Grey land is not yet researched. Sub-national rules for Canada, Australia and the UAE are summarised at country level and listed in each record; the US states level covers all 50 states and the District of Columbia. Small territories are drawn as markers. Water-quality values are for chlorinated fresh-water pools.</p>
</div>
<aside class="panel" id="panel" role="dialog" aria-label="Jurisdiction record" aria-hidden="true"></aside>

`;
(function(){
  function navOffset(){
    var nav=document.querySelector('.w-nav, nav'); var h=0;
    if(nav){ var cs=getComputedStyle(nav); if(cs.position==='sticky'||cs.position==='fixed'){ h=Math.round(nav.getBoundingClientRect().height); } }
    root.style.setProperty('--arcm-sticky-top', h+'px');
  }
  navOffset(); window.addEventListener('resize', navOffset); window.addEventListener('load', navOffset);
})();
/* ===================== DATA ===================== */
// gate: none|notify|approve · cert: req|none|advised · process: closed|clause|silent · conf: verified|secondary|inferred
var J = [
 // ---------- North America ----------
 {id:'USA',name:'United States',region:'North America',rk:'na',gate:'approve',cert:'req',process:'silent',fcMin:1.0,fcMax:10,ph:'7.2–7.8',ahj:'State or local health department; building official in FL and TX',conf:'verified',card:'us-fed',trig:'Any "kills / controls" wording makes it an EPA FIFRA pesticide device; Texas adds FIFRA registration if classed a supplemental treatment system; Florida and Puerto Rico require NSF-pw marking on recirculation plastics.',
  cert_t:'MAHC, ISPSC and USPSHTC all require equipment certified to NSF/ANSI 50 by an ANSI-accredited body. The IAPMO R&T certificate qualifies everywhere.',proc_t:'MAHC "supplemental treatment" means disinfection; AquaRev sits outside it. Never claim kill/control (EPA FIFRA device rule).',inst_t:'Written approval or plan review before altering an existing pool is the rule in 35 states and DC; a notice or scope-of-work suffices in nine (AZ, FL, NY, TX, HI, OK, OR, WY, NM); no state requirement in AK, ID, KS, MS, ND and VT, where local ordinance governs. Switch to the US states level for each state.',
  path:'Every installation is supplied with an authority documentation package: certification listing W-12547, specification sheet, 2.6 psi head-loss data and a statement that free-chlorine and pH targets are unchanged.',subs:'usa'},
 {id:'CAN',name:'Canada',region:'North America',rk:'na',gate:'approve',cert:'none',process:'silent',fcMin:0.5,fcMax:10,ph:'7.2–7.8',ahj:'Provincial or regional health authority',conf:'verified',card:'ca-on',
  cert_t:'NSF/ANSI/CAN 50 is a National Standard of Canada but no provincial pool regulation names an equipment standard.',proc_t:'No approval clause for non-disinfecting devices in ON, BC, AB or QC.',inst_t:'Alberta: mandatory written AHS approval (form 19381). Ontario: building permit plus 14-day PHI notice and written reopening permission. BC: construction permit or s.5(6) minor-alteration waiver. Quebec: none.',
  path:'Written approval is obtained before installation in Alberta, Ontario and British Columbia; documentation is supplied in French for Quebec.',subs:'can'},
 {id:'MEX',name:'Mexico',region:'North America',rk:'na',gate:'none',cert:'none',process:'silent',fcMin:1.0,fcMax:5.0,ph:'6.5–8.5',ahj:'COFEPRIS / state COEPRIS',conf:'verified',card:'mx',
  cert_t:'NOM-245-SSA1-2010 requires circulation and filtration but names no equipment standard.',proc_t:'Chlorine, bromine or ORP accepted; no device approval.',inst_t:'No sanitary permit for equipment changes.',path:'No regulatory requirement applies; installations are documented against NOM-245 and the hotel group\'s engineering standards.'},
 {id:'PRI',name:'Puerto Rico',region:'North America',rk:'carib',gate:'notify',cert:'req',process:'silent',fcMin:1.0,fcMax:5.0,ph:'7.2–7.8',ahj:'Salud Ambiental + OGPe',conf:'verified',card:'pr',ll:[18.2,-66.5],trig:'NSF-pw marking required on plastic pipe in the recirculation system.',
  cert_t:'Reglamento General de Salud Ambiental: equipment "deberá cumplir con las disposiciones de la NSF"; plastic pipe must bear the NSF-pw logo.',proc_t:'Silent on passive devices.',inst_t:'Secretary may require plans for remodeling; annual sanitary licence.',path:'The Florida documentation package is supplied in Spanish, including the pipe-marking statement.'},
 {id:'JAM',name:'Jamaica',region:'North America',rk:'carib',gate:'notify',cert:'none',process:'clause',fcMin:0.5,fcMax:null,ph:'7.5–7.8',ahj:'Parish Medical Officer (Health)',conf:'verified',card:'carib',
  cert_t:'Public Health (Swimming Pools) Regulations 2000: no equipment standard.',proc_t:'Only ozone and electrolytic processes need MOH approval.',inst_t:'MOH operating permit; courtesy notice on plant change.',path:'Courtesy notice to the parish MOH.'},
 {id:'BRB',name:'Barbados',region:'North America',rk:'carib',gate:'approve',cert:'none',process:'clause',fcMin:0.5,fcMax:null,ph:'7.5–8.4',ahj:'Senior Medical Officer of Health',conf:'verified',card:'carib',ll:[13.2,-59.5],
  cert_t:'Health Services (Swimming Pools) Regulations 1970: no equipment standard.',proc_t:'Disinfectant introduced by SMOH-approved methods (reg. 14(4)).',inst_t:'Reg. 4(1): no construction or alteration without plans and written SMOH approval.',path:'SMOH approval letter before install.'},
 {id:'CYM',name:'Cayman Islands',region:'North America',rk:'carib',gate:'approve',cert:'none',process:'silent',fcMin:1.0,fcMax:10,ph:'7.2–7.8',ahj:'Department of Environmental Health',conf:'verified',card:'carib',ll:[19.3,-81.3],
  cert_t:'DEH Development Control Guidelines (2009); ISPSC referenced.',proc_t:'Silent.',inst_t:'§4.2.1: no pool installation, alteration or repair without a DEH permit.',path:'A DEH permit or notice precedes installation.'},
 {id:'BHS',name:'Bahamas',region:'North America',rk:'carib',gate:'none',cert:'none',process:'silent',fcMin:null,fcMax:null,ph:'—',ahj:'Dept of Environmental Health Services',conf:'inferred',card:'carib',
  cert_t:'No pool-specific regulation located under the Environmental Health Services Act 1987.',proc_t:'Discretionary; CDC/MAHC norms in practice.',inst_t:'Hotels need a DEHS Certificate of Sanitation.',path:'DEHS inspector letter with the listing.'},
 {id:'DOM',name:'Dominican Republic',region:'North America',rk:'carib',gate:'none',cert:'none',process:'silent',fcMin:null,fcMax:null,ph:'—',ahj:'Ministerio de Salud Pública / MITUR',conf:'inferred',card:'carib',
  cert_t:'No pool NORDOM located.',proc_t:'Discretionary.',inst_t:'Hotel classification inspections.',path:'The hotel group\'s engineering standard and the NSF 50 listing govern the installation.'},
 {id:'TCA',name:'Turks & Caicos',region:'North America',rk:'carib',gate:'none',cert:'none',process:'silent',fcMin:null,fcMax:null,ph:'—',ahj:'Environmental Health Department',conf:'inferred',card:'carib',ll:[21.7,-71.8],
  cert_t:'Published pool standards "coming soon" on gov.tc.',proc_t:'Discretionary.',inst_t:'Contact EHD.',path:'EHD courtesy letter.'},
 {id:'VIR',name:'US Virgin Islands',region:'North America',rk:'carib',gate:'none',cert:'none',process:'silent',fcMin:null,fcMax:null,ph:'—',ahj:'VI DOH Environmental Health / DPNR',conf:'inferred',card:'carib',ll:[18.3,-64.9],
  cert_t:'No territorial pool code located.',proc_t:'CDC/MAHC-based discretion expected.',inst_t:'DPNR building permits for structural work only.',path:'Contact VI DOH Environmental Health.'},
 {id:'ABW',name:'Aruba',region:'North America',rk:'carib',gate:'none',cert:'none',process:'silent',fcMin:null,fcMax:null,ph:'—',ahj:'Departamento di Salud Publico',conf:'inferred',card:'carib',ll:[12.5,-70.0],
  cert_t:'No published equipment or chemistry regulation found.',proc_t:'Discretionary.',inst_t:'Hotel inspections.',path:'The hotel group\'s engineering standard and the NSF 50 listing govern the installation.'},
 // ---------- Europe ----------
 {id:'DEU',name:'Germany',region:'Europe',rk:'eu',gate:'notify',cert:'none',process:'closed',fcMin:0.3,fcMax:0.6,ph:'6.5–7.5',ahj:'Gesundheitsamt',conf:'verified',card:'de',trig:'Hygienic-technical expert report (Gutachten) if the Gesundheitsamt treats it as a DIN 19643 deviation.',
  cert_t:'No product approval; PED sound-engineering-practice, no CE mark.',proc_t:'§37 IfSG plus DIN 19643 as recognised rules of technology; the standard lists permitted process combinations. AquaRev adds no stage, so it is not a deviation, but expect a Sachverständiger opinion request.',inst_t:'UBA recommendation: operator informs the Gesundheitsamt of significant changes before commissioning.',path:'AquaRev supplies a DIN 19643 non-interference statement and, where requested, a Sachverständiger opinion; the operator notifies the Gesundheitsamt and records bacteriology for four to eight weeks.'},
 {id:'GBR',name:'United Kingdom',region:'Europe',rk:'eu',gate:'none',cert:'none',process:'silent',fcMin:0.5,fcMax:3.0,ph:'7.0–7.4',ahj:'Operator (PWTAG / HSE HSG179)',conf:'verified',card:'uk',
  cert_t:'Pressure Equipment (Safety) Regs 2016: below threshold, no UKCA mark. WRAS not applicable.',proc_t:'No statutory standard; PWTAG Code of Practice governs and already accepts NSF/ANSI 50 validation for UV.',inst_t:'None. Operator updates the Pool Safety Operating Procedure.',path:'Described as supplementary conditioning compatible with the PWTAG Code of Practice and validated to NSF/ANSI 50; the operator adds it to the Pool Safety Operating Procedure.'},
 {id:'FRA',name:'France',region:'Europe',rk:'eu',gate:'notify',cert:'none',process:'clause',fcMin:0.4,fcMax:1.4,ph:'6.9–7.7',ahj:'ARS (Agence régionale de santé)',conf:'verified',card:'fr',trig:'ANSES authorisation (CSP D.1332-3) if the device is presented as a disinfection process, chlorine stabiliser or chloramine-reduction process. Keep chloramine claims out of French materials.',
  cert_t:'No product approval; ACS is drinking-water only.',proc_t:'CSP D.1332-3: ANSES authorises disinfection processes, chlorine stabilisers and dechloramination processes. A device that claims none of these needs no authorisation. Any chloramine-reduction claim triggers an ANSES dossier.',inst_t:'Mairie declaration; ARS contrôle sanitaire; report the change in the ARS file.',path:'Presented in France solely as hydraulic conditioning that reduces chlorine consumption; no chloramine-reduction claim is made. The operator records it in the surveillance file and informs the ARS.'},
 {id:'ESP',name:'Spain',region:'Europe',rk:'eu',gate:'none',cert:'none',process:'silent',fcMin:0.5,fcMax:2.0,ph:'7.2–8.0',ahj:'Regional health authority (CCAA)',conf:'verified',card:'es',
  cert_t:'None.',proc_t:'RD 742/2013: biocides must be registered TP2 products; no closed list of processes.',inst_t:'Opening notified; modification reporting is regional.',path:'AquaRev supplies a not-a-biocide statement; the operator adds the device to the autocontrol protocol.'},
 {id:'ITA',name:'Italy',region:'Europe',rk:'eu',gate:'notify',cert:'none',process:'clause',fcMin:0.7,fcMax:1.5,ph:'6.5–7.5',ahj:'ASL / Comune',conf:'secondary',card:'it',
  cert_t:'UNI 10637 governs plant design; no certification.',proc_t:'Disinfectants must be Ministero della Salute-authorised; no process list.',inst_t:'Update the autorizzazione/SCIA file and manuale di autocontrollo per regional law.',path:'UNI 10637 compatibility statement; comunicazione with ASL where required.'},
 {id:'NLD',name:'Netherlands',region:'Europe',rk:'eu',gate:'notify',cert:'none',process:'silent',fcMin:0.5,fcMax:1.5,ph:'7.0–7.6',ahj:'Omgevingsdienst (for Gedeputeerde Staten)',conf:'verified',card:'nl',
  cert_t:'None.',proc_t:'Bal §15.2.1 is goal-based; risicoanalyse and beheersplan show how art. 15.16 is met.',inst_t:'Art. 15.13 melding at least four weeks before; re-notify when the activity changes.',path:'Amended melding plus updated beheersplan four weeks before install.'},
 {id:'AUT',name:'Austria',region:'Europe',rk:'eu',gate:'approve',cert:'none',process:'closed',fcMin:0.3,fcMax:null,ph:'6.5–7.8',ahj:'Bezirksverwaltungsbehörde',conf:'verified',card:'at',trig:'Written opinion that the device sits outside the §14 BHygV process list, filed with the Änderungsanzeige.',
  cert_t:'None; ÖNORM M 6215 technical reference.',proc_t:'Bäderhygieneverordnung §14 enumerates permitted process combinations; the strictest list in Europe.',inst_t:'Errichtungs- and Betriebsbewilligung regime; plant changes need an Änderungsanzeige with an Amtssachverständiger opinion.',path:'Written opinion that the device is a hydraulic accessory outside §14; Änderungsanzeige before install.'},
 {id:'CHE',name:'Switzerland',region:'Europe',rk:'eu',gate:'none',cert:'none',process:'closed',fcMin:0.2,fcMax:0.8,ph:'6.8–7.6',ahj:'Cantonal food inspectorate',conf:'verified',card:'ch',
  cert_t:'None.',proc_t:'TBDV Art. 10: only Annex 5a substances and processes for disinfection; Art. 13: plants per SIA 385/9. A non-disinfecting device is outside Art. 10.',inst_t:'Operator Selbstkontrolle; cantonal permits vary.',path:'SIA 385/9 compatibility note.'},
 {id:'PRT',name:'Portugal',region:'Europe',rk:'eu',gate:'notify',cert:'none',process:'silent',fcMin:0.5,fcMax:2.0,ph:'6.9–8.0',ahj:'ARS / Delegado de Saúde',conf:'verified',card:'pt',
  cert_t:'NP EN 15288 adopted; CNQ 23/93 still the treatment reference.',proc_t:'Treatment types defined; isocyanurates homologated.',inst_t:'Vigilância Sanitária programme; no explicit modification rule found.',path:'Compatibility note; inform the Delegado de Saúde.'},
 {id:'GRC',name:'Greece',region:'Europe',rk:'eu',gate:'notify',cert:'none',process:'clause',fcMin:0.4,fcMax:0.7,ph:'7.2–8.2',ahj:'Health Service via EUGO notification',conf:'verified',card:'gr',
  cert_t:'None.',proc_t:'Γ1/443/1973 Art. 18: continuous chlorination; non-chlorine methods need approval. AquaRev keeps chlorination.',inst_t:'Operating licence is now a γνωστοποίηση; file a change of details.',path:'Update the γνωστοποίηση.'},
 {id:'DNK',name:'Denmark',region:'Europe',rk:'eu',gate:'approve',cert:'none',process:'clause',fcMin:0.4,fcMax:1.5,ph:'6.8–7.6',ahj:'Kommune',conf:'verified',card:'dk',trig:'Municipal approval (tillægsgodkendelse) if the change "materially affects hygiene" under §3.',
  cert_t:'None; DS 477 norm.',proc_t:'BEK 918/2016: other disinfection principles only by municipal derogation.',inst_t:'§3: no operational or plant change materially affecting hygiene without prior municipal approval.',path:'Ask the kommune; expect a tillægsgodkendelse letter.'},
 {id:'SWE',name:'Sweden',region:'Europe',rk:'eu',gate:'notify',cert:'none',process:'silent',fcMin:0.4,fcMax:2.0,ph:'7.2–7.6',ahj:'Municipal miljökontor',conf:'verified',card:'se',
  cert_t:'None.',proc_t:'HSLF-FS 2021:11 guideline values; no process list.',inst_t:'Anmälan under förordning 1998:899; egenkontroll.',path:'Document in egenkontroll; inform the miljökontor.'},
 {id:'NOR',name:'Norway',region:'Europe',rk:'eu',gate:'notify',cert:'none',process:'silent',fcMin:0.4,fcMax:3.0,ph:'7.2–7.6',ahj:'Kommune',conf:'verified',card:'no',
  cert_t:'None.',proc_t:'Forskrift for badeanlegg; no process list.',inst_t:'§6 melding before start and before changes.',path:'File a §6 melding.'},
 {id:'POL',name:'Poland',region:'Europe',rk:'eu',gate:'notify',cert:'advised',process:'silent',fcMin:0.3,fcMax:0.6,ph:'6.5–7.6',ahj:'Państwowy Powiatowy Inspektor Sanitarny',conf:'verified',card:'pl',
  cert_t:'No legal certification, but operators routinely ask for a voluntary NIZP-PZH hygienic certificate.',proc_t:'Ministerial regulation of 9 Nov 2015 sets parameters; no process list.',inst_t:'Manager reports to the PPIS within three working days.',path:'A voluntary NIZP-PZH hygienic certificate is provided; the operator informs the PPIS.'},
 {id:'TUR',name:'Turkey',region:'Europe',rk:'eu',gate:'none',cert:'none',process:'clause',fcMin:1.0,fcMax:3.0,ph:'6.5–7.8',ahj:'İl Sağlık Müdürlüğü',conf:'verified',card:'tr',
  cert_t:'None; PED transposition means no CE.',proc_t:'Art. 14: only Ministry-licensed disinfectants and chemicals; the device is not a chemical.',inst_t:'Monthly inspection; no device-level notice.',path:'Log the device for inspection.'},
 // ---------- Middle East & Africa ----------
 {id:'ARE',name:'United Arab Emirates',region:'Middle East & Africa',rk:'me',gate:'approve',cert:'none',process:'silent',fcMin:1.0,fcMax:10,ph:'7.2–7.6',ahj:'Dubai Municipality H&S / Trakhees; Abu Dhabi municipality Public Health',conf:'verified',card:'ae-dxb',
  cert_t:'Dubai GU81 cites BS EN 15288 and 13451; no NSF 50. ECAS and Dubai Central Lab schemes do not cover pool devices.',proc_t:'Automatic dosing mandatory; silent on passive devices.',inst_t:'Dubai GU81 §4-4: no alteration or modification without DM approval, with a hazard assessment. Abu Dhabi §4(1): no modifications without licence amendment.',path:'File as a minor plant modification with the listing; Trakhees NOC in PCFC areas.',subs:'uae'},
 {id:'SAU',name:'Saudi Arabia',region:'Middle East & Africa',rk:'me',gate:'notify',cert:'advised',process:'silent',fcMin:1.0,fcMax:3.0,ph:'7.2–7.8',ahj:'Balady municipality; SBC 1401',conf:'inferred',card:'sa',trig:'SABER conformity certificate if the device\'s HS code falls under a SASO technical regulation.',
  cert_t:'SABER conformity is mandatory for electrical pool products; whether a PVC device is captured depends on its HS classification. SBC 1401 Swimming Pool and Spa Code (2024) is ISPSC-derived.',proc_t:'No MoH pre-approval list found.',inst_t:'Municipal licence; SBC 1401 covers modification.',path:'Import conformity is confirmed with a SABER-approved body for the device\'s customs classification; documented under SBC 1401 as NSF 50-listed equipment.'},
 {id:'QAT',name:'Qatar',region:'Middle East & Africa',rk:'me',gate:'notify',cert:'none',process:'clause',fcMin:1.0,fcMax:4.0,ph:'7.2–7.8',ahj:'Ministry of Public Health',conf:'verified',card:'qa',
  cert_t:'MOPH recreational-water guideline names no product standard.',proc_t:'Automatic disinfection required; reduced FC with ozone/UV needs MOPH approval.',inst_t:'MOPH operating permit, renewed.',path:'Notify the MOPH Environmental Health Section at renewal.'},
 {id:'OMN',name:'Oman',region:'Middle East & Africa',rk:'me',gate:'none',cert:'none',process:'silent',fcMin:null,fcMax:null,ph:'—',ahj:'Municipality + MoH',conf:'inferred',card:'gulf',cert_t:'No official text retrieved.',proc_t:'Expected GCC-typical.',inst_t:'Municipality NOC via contractor.',path:'Carry the NSF 50 file.'},
 {id:'BHR',name:'Bahrain',region:'Middle East & Africa',rk:'me',gate:'none',cert:'none',process:'silent',fcMin:1.0,fcMax:3.0,ph:'6.8–7.8',ahj:'Ministry of Health',conf:'verified',card:'gulf',ll:[26.1,50.6],cert_t:'MoH 2021 pool measures: approved chemicals, dosing equipment, records.',proc_t:'Silent on devices.',inst_t:'Inspection record.',path:'Inform MoH environmental health at inspection.'},
 {id:'KWT',name:'Kuwait',region:'Middle East & Africa',rk:'me',gate:'none',cert:'none',process:'silent',fcMin:null,fcMax:null,ph:'—',ahj:'MoH / MoCI',conf:'secondary',card:'gulf',cert_t:'KUCAS regulated list is electrical and consumer goods.',proc_t:'2025 MoH/MoCI health guide sets chlorine limits (table not retrieved).',inst_t:'Facility licence.',path:'The facility licence holder informs the Ministry of Health; values follow the 2025 MoH guide.'},
 {id:'JOR',name:'Jordan',region:'Middle East & Africa',rk:'me',gate:'none',cert:'none',process:'silent',fcMin:1.0,fcMax:2.0,ph:'7.2–7.8',ahj:'Ministry of Health',conf:'secondary',card:'gulf',cert_t:'JS 1562/2004 pool water standard.',proc_t:'Silent.',inst_t:'MoH monitoring.',path:'No registration.'},
 {id:'EGY',name:'Egypt',region:'Middle East & Africa',rk:'af',gate:'none',cert:'none',process:'silent',fcMin:1.0,fcMax:3.0,ph:'7.2–7.6',ahj:'MoHP / Ministry of Tourism',conf:'secondary',card:'gulf',cert_t:'ES 418/1995 pool water; GOEIC registration does not list pool devices.',proc_t:'Silent.',inst_t:'MoHP inspection.',path:'Import as a non-regulated fitting.'},
 {id:'ISR',name:'Israel',region:'Middle East & Africa',rk:'me',gate:'notify',cert:'none',process:'clause',fcMin:0.8,fcMax:2.0,ph:'7.2–7.6',ahj:'MoH district engineer',conf:'verified',card:'il',cert_t:'Business Licensing Regulations 5754-1994 mandate no equipment standard.',proc_t:'§6: alternative disinfectants need Director approval; a non-disinfecting device is outside.',inst_t:'Notify the district health office.',path:'Present as a non-disinfecting hydrodynamic conditioner.'},
 {id:'MAR',name:'Morocco',region:'Middle East & Africa',rk:'af',gate:'none',cert:'none',process:'silent',fcMin:null,fcMax:null,ph:'—',ahj:'MoH provincial hygiene services',conf:'inferred',card:'africa',cert_t:'No NM certification for pool devices.',proc_t:'Silent.',inst_t:'Tourism classification inspections.',path:'Contractor-led install; French documentation.'},
 {id:'TUN',name:'Tunisia',region:'Middle East & Africa',rk:'af',gate:'none',cert:'none',process:'silent',fcMin:null,fcMax:null,ph:'—',ahj:'MoH hygiene directorate / ONTT',conf:'inferred',card:'africa',cert_t:'None.',proc_t:'French-style values likely referenced.',inst_t:'None found.',path:'Contractor-led install.'},
 {id:'ZAF',name:'South Africa',region:'Middle East & Africa',rk:'af',gate:'notify',cert:'none',process:'silent',fcMin:0.5,fcMax:3.0,ph:'7.2–7.8',ahj:'Municipal Environmental Health Practitioner',conf:'verified',card:'za',cert_t:'National Environmental Health Norms and Standards (2015); no SABS/NRCS compulsory spec.',proc_t:'Silent beyond residuals.',inst_t:'Health Certificate from the EHP; by-laws vary.',path:'Inform the municipal EHP.'},
 {id:'KEN',name:'Kenya',region:'Middle East & Africa',rk:'af',gate:'none',cert:'advised',process:'silent',fcMin:1.0,fcMax:3.0,ph:'7.2–7.6',ahj:'County public health officer',conf:'secondary',card:'africa',cert_t:'KEBS KS 2595:2015 and KS 2793 exist; PVoC import inspection applies.',proc_t:'Silent.',inst_t:'County licensing.',path:'PVoC certificate on shipment.'},
 {id:'TZA',name:'Tanzania',region:'Middle East & Africa',rk:'af',gate:'none',cert:'advised',process:'silent',fcMin:null,fcMax:null,ph:'—',ahj:'MoH / Zanzibar tourism commission',conf:'inferred',card:'africa',cert_t:'TBS PVoC on import.',proc_t:'WHO ranges.',inst_t:'None.',path:'PVoC plus contractor install.'},
 {id:'MUS',name:'Mauritius',region:'Middle East & Africa',rk:'af',gate:'none',cert:'none',process:'silent',fcMin:null,fcMax:null,ph:'—',ahj:'Tourism Authority / MoH',conf:'secondary',card:'africa',ll:[-20.3,57.6],cert_t:'Tourism licence requires health and fire clearances.',proc_t:'WHO ranges.',inst_t:'None.',path:'The hotel group\'s engineering standard and the NSF 50 listing govern the installation.'},
 {id:'SYC',name:'Seychelles',region:'Middle East & Africa',rk:'af',gate:'none',cert:'none',process:'silent',fcMin:null,fcMax:null,ph:'—',ahj:'Tourism Department / Public Health Authority',conf:'verified',card:'africa',ll:[-4.6,55.5],cert_t:'Tourism Development (Standards) Regulations 2023: daily pH and chlorine checks recorded; no numeric values.',proc_t:'Silent.',inst_t:'None.',path:'The hotel group\'s engineering standard and the NSF 50 listing govern the installation.'},
 {id:'NGA',name:'Nigeria',region:'Middle East & Africa',rk:'af',gate:'none',cert:'none',process:'silent',fcMin:null,fcMax:null,ph:'—',ahj:'State MoH',conf:'inferred',card:'africa',cert_t:'SONCAP covers regulated categories; passive PVC likely outside.',proc_t:'Silent.',inst_t:'None.',path:'Contractor install.'},
 // ---------- Asia-Pacific ----------
 {id:'AUS',name:'Australia',region:'Asia-Pacific',rk:'apac',gate:'none',cert:'none',process:'silent',fcMin:1.0,fcMax:10,ph:'7.2–7.8',ahj:'State health department + local council',conf:'verified',card:'au',
  cert_t:'WaterMark does not capture the pool return loop; no state guideline references NSF 50; disinfectants are APVMA-registered but a device is not.',proc_t:'Chlorine or bromine primary; adjuncts welcomed; no approval for a passive adjunct.',inst_t:'NSW, QLD, VIC: none (the water-quality risk plan is updated). WA: the plant is CHO-approved, so WA Health is written to before installation.',path:'The IAPMO listing serves as third-party certification; a written WaterMark not-required opinion is available for procurement files, and WA Health confirmation is obtained for Western Australian installations.',subs:'aus'},
 {id:'NZL',name:'New Zealand',region:'Asia-Pacific',rk:'apac',gate:'none',cert:'none',process:'silent',fcMin:1.5,fcMax:7.0,ph:'7.2–8.0',ahj:'Territorial authority',conf:'secondary',card:'nz',cert_t:'NZS 4441 and NZS 5826 are voluntary; PoolSafe accreditation.',proc_t:'NZS 5826 §2.13 contemplates alternative treatment alongside chlorine.',inst_t:'Building Act Sch. 1 exemptions for plant changes.',path:'PoolSafe-ready O&M sheet.'},
 {id:'SGP',name:'Singapore',region:'Asia-Pacific',rk:'apac',gate:'notify',cert:'none',process:'clause',fcMin:1.0,fcMax:3.0,ph:'7.2–7.8',ahj:'National Environment Agency',conf:'verified',card:'sg',ll:[1.35,103.8],cert_t:'S 644/2021 names no equipment standard.',proc_t:'Reg. 4: only listed chlorine/bromine or a chemical approved by the Director-General. A device is not a chemical.',inst_t:'Licence rests on a PE-endorsed schematic; submit an updated schematic.',path:'PE sign-off on the amended schematic to NEA.'},
 {id:'HKG',name:'Hong Kong',region:'Asia-Pacific',rk:'apac',gate:'approve',cert:'none',process:'silent',fcMin:1.0,fcMax:3.0,ph:'7.2–7.8',ahj:'Food and Environmental Hygiene Department',conf:'verified',card:'hk',ll:[22.3,114.2],cert_t:'Cap. 132CA licence; no equipment standard.',proc_t:'Silent on disinfection technology.',inst_t:'Licensing Condition 1: no alteration or addition without prior FEHD approval.',path:'Authorized Person files a minor-alteration application with amended schematic.'},
 {id:'JPN',name:'Japan',region:'Asia-Pacific',rk:'apac',gate:'approve',cert:'none',process:'silent',fcMin:0.4,fcMax:1.0,ph:'5.8–8.6',ahj:'保健所 (prefectural health centre)',conf:'verified',card:'jp',cert_t:'MHLW hygiene standard mandates no JIS or third-party certification.',proc_t:'Chlorine baseline; ozone/UV may supplement.',inst_t:'Prefectural ordinances require a 変更届 for equipment changes; consult the 保健所 first.',path:'変更届 before install with a Japanese translation of the listing.'},
 {id:'CHN',name:'China',region:'Asia-Pacific',rk:'apac',gate:'notify',cert:'none',process:'clause',fcMin:0.3,fcMax:1.0,ph:'7.0–7.8',ahj:'County 卫生健康 authority',conf:'secondary',card:'cn',trig:'消毒产品 hygiene evaluation and filing if any disinfection claim is made.',cert_t:'GB 37488-2019 water limits; no CCC for passive plumbing.',proc_t:'消毒管理办法 captures products that claim disinfection. Never market as a 消毒 device.',inst_t:'Update the 卫生设施平面布局图 and annual test report; no re-licence.',path:'Import as a general PVC fitting; avoid disinfection claims.'},
 {id:'KOR',name:'South Korea',region:'Asia-Pacific',rk:'apac',gate:'none',cert:'none',process:'silent',fcMin:0.4,fcMax:1.0,ph:'5.8–8.6',ahj:'City / county office',conf:'verified',card:'kr',cert_t:'KC mark covers electrical and household goods only.',proc_t:'Sports Facilities Act hygiene table; no restriction on supplementary treatment.',inst_t:'변경신고 only if reported facility items change.',path:'No approval is required; the installer confirms the reported facility particulars (신고) are unchanged.'},
 {id:'THA',name:'Thailand',region:'Asia-Pacific',rk:'apac',gate:'none',cert:'none',process:'silent',fcMin:1.0,fcMax:3.0,ph:'7.2–7.6',ahj:'Local authority (hazardous-business licence)',conf:'secondary',card:'sea',cert_t:'TIS marks voluntary.',proc_t:'Local ordinances; no device approval.',inst_t:'Annual licence; equipment changes not a licence event.',path:'Log in the plant-room record.'},
 {id:'MYS',name:'Malaysia',region:'Asia-Pacific',rk:'apac',gate:'none',cert:'none',process:'silent',fcMin:0.5,fcMax:3.0,ph:'7.0–7.8',ahj:'Local council (PBT)',conf:'secondary',card:'sea',cert_t:'SIRIM voluntary; SPAN covers potable products only.',proc_t:'MOH monitoring guideline only.',inst_t:'Check the PBT by-law for an alteration clause.',path:'Install and log.'},
 {id:'IDN',name:'Indonesia',region:'Asia-Pacific',rk:'apac',gate:'none',cert:'none',process:'silent',fcMin:1.0,fcMax:1.5,ph:'7.0–7.8',ahj:'Dinas Kesehatan',conf:'secondary',card:'sea',cert_t:'Permenkes 32/2017 regulates water, not equipment.',proc_t:'Silent.',inst_t:'Laik Sehat file updated at inspection.',path:'Bahasa O&M sheet.'},
 {id:'PHL',name:'Philippines',region:'Asia-Pacific',rk:'apac',gate:'none',cert:'none',process:'silent',fcMin:0.5,fcMax:1.0,ph:'7.2–7.8',ahj:'City / municipal health officer',conf:'verified',card:'sea',cert_t:'PD 856 Ch. VIII; no equipment standard.',proc_t:'Silent.',inst_t:'Annual sanitary permit; no plant-alteration approval.',path:'Note the device in the permit file.'},
 {id:'VNM',name:'Vietnam',region:'Asia-Pacific',rk:'apac',gate:'none',cert:'none',process:'silent',fcMin:0.2,fcMax:1.0,ph:'6.0–8.5',ahj:'Provincial Sở VHTTDL',conf:'secondary',card:'sea',cert_t:'None.',proc_t:'QCVN 01-1:2018/BYT water quality.',inst_t:'Eligibility certificate unaffected.',path:'Vietnamese O&M sheet.'},
 {id:'IND',name:'India',region:'Asia-Pacific',rk:'apac',gate:'none',cert:'none',process:'silent',fcMin:0.2,fcMax:0.5,ph:'7.5–8.5',ahj:'Police / municipal licensing',conf:'verified',card:'in',cert_t:'IS 3328:1993 voluntary; no BIS QCO for pool devices.',proc_t:'Silent.',inst_t:'Annual licence with lab report.',path:'An IS 3328 test report accompanies licence renewal; the 41% figure is expressed as a reduction in chlorine demand, never of the regulated residual.'},
 {id:'MDV',name:'Maldives',region:'Asia-Pacific',rk:'apac',gate:'none',cert:'none',process:'silent',fcMin:null,fcMax:null,ph:'—',ahj:'Ministry of Tourism / HPA',conf:'inferred',card:'islands',ll:[3.2,73.2],cert_t:'Tourism regulations cover safety, not chemistry.',proc_t:'WHO ranges.',inst_t:'None.',path:'No regulator approval applies; the listing and WHO-aligned operating documentation are supplied to the resort\'s engineering team.'},
 {id:'FJI',name:'Fiji',region:'Asia-Pacific',rk:'apac',gate:'none',cert:'none',process:'silent',fcMin:null,fcMax:null,ph:'—',ahj:'MoH environmental health',conf:'inferred',card:'islands',cert_t:'Public Health Act 1935 general powers.',proc_t:'WHO ranges.',inst_t:'None.',path:'Contractor install.'},
 {id:'PYF',name:'French Polynesia',region:'Asia-Pacific',rk:'apac',gate:'none',cert:'none',process:'silent',fcMin:null,fcMax:null,ph:'—',ahj:'Direction de la santé',conf:'inferred',card:'islands',ll:[-17.5,-149.5],cert_t:'Territorial competence; metropolitan values not automatic.',proc_t:'Local arrêtés.',inst_t:'None found.',path:'Contractor install.'},
 // ---------- Latin America ----------
 {id:'BRA',name:'Brazil',region:'Latin America',rk:'latam',gate:'notify',cert:'none',process:'silent',fcMin:0.8,fcMax:3.0,ph:'7.2–7.8',ahj:'Vigilância Sanitária (state/municipal)',conf:'secondary',card:'br',cert_t:'ABNT NBR 10339 and 10818 voluntary; INMETRO covers drinking-water appliances only.',proc_t:'ANVISA saneantes are chemicals; device outside.',inst_t:'SP Código Sanitário Art. 117 ties operation to the approved project; file a project note.',path:'One-page alteração de projeto with the local VISA.'},
 {id:'ARG',name:'Argentina',region:'Latin America',rk:'latam',gate:'approve',cert:'none',process:'clause',fcMin:0.4,fcMax:0.6,ph:'7.2–7.8',ahj:'AGC (CABA) / municipal bromatology',conf:'verified',card:'ar',trig:'CABA habilitación lists approved water-treatment equipment; an addendum with the NSF 50 certificate is needed.',cert_t:'No IRAM pool-equipment standard; ANMAT covers chemicals.',proc_t:'CABA habilitación requires a certificate of approval for water-treatment equipment.',inst_t:'Addendum to the equipment certificate on file.',path:'Submit the NSF 50 certificate to the AGC as an addendum.'},
 {id:'CHL',name:'Chile',region:'Latin America',rk:'latam',gate:'approve',cert:'none',process:'clause',fcMin:0.5,fcMax:1.5,ph:'7.2–8.2',ahj:'SEREMI de Salud',conf:'verified',card:'cl',cert_t:'D.S. 209/2002; no product certification.',proc_t:'Art. 15: chlorine or a disinfectant approved by the health service.',inst_t:'Art. 9: any modification must be expressly authorised.',path:'Solicitud de autorización de modificación under Art. 9.'},
 {id:'COL',name:'Colombia',region:'Latin America',rk:'latam',gate:'none',cert:'none',process:'silent',fcMin:1.0,fcMax:3.0,ph:'7.0–8.0',ahj:'Secretaría de Salud',conf:'verified',card:'co',cert_t:'Only safety devices need homologation.',proc_t:'INVIMA registration for chemical disinfectants only.',inst_t:'Safety-plan entry; annual sampling.',path:'Add the device to the equipment register.'},
 {id:'PER',name:'Peru',region:'Latin America',rk:'latam',gate:'approve',cert:'none',process:'silent',fcMin:0.4,fcMax:1.2,ph:'6.5–8.5',ahj:'DIRESA / DIGESA',conf:'verified',card:'pe',cert_t:'D.S. 007-2003-SA; Art. 45 favours low-head-loss union-joined accessories.',proc_t:'Art. 47 automatic disinfection device mandatory; silent on conditioners.',inst_t:'Art. 12: any change communicated for approval.',path:'Comunicación de modificación to the DIRESA.'},
 {id:'CRI',name:'Costa Rica',region:'Latin America',rk:'latam',gate:'notify',cert:'none',process:'silent',fcMin:1.2,fcMax:3.0,ph:'6.8–8.0',ahj:'Área Rectora de Salud',conf:'verified',card:'cr',cert_t:'Decreto 35309-S; chemicals registered; device is not a chemical.',proc_t:'Non-residual disinfection must be paired with a residual product.',inst_t:'Art. 4(a): modification under the sanitary-permit regulation.',path:'Notify the Área Rectora at PSF renewal or amendment.'},
 {id:'URY',name:'Uruguay',region:'Latin America',rk:'latam',gate:'approve',cert:'none',process:'closed',fcMin:0.4,fcMax:0.6,ph:'7.0–8.0',ahj:'Servicio de Salubridad (Montevideo)',conf:'verified',card:'uy',trig:'"Any other method of water hygiene" needs Servicio de Salubridad approval (D.3649); get a written no-objection first.',cert_t:'None.',proc_t:'Art. D.3649: any other water-hygiene method must be approved by the health service. Strictest wording in the region.',inst_t:'Habilitación after inspection.',path:'A written no-objection from the Servicio de Salubridad is obtained before installation.'},
 {id:'PAN',name:'Panama',region:'Latin America',rk:'latam',gate:'none',cert:'none',process:'silent',fcMin:null,fcMax:null,ph:'—',ahj:'MINSA local health centre',conf:'secondary',card:'latam-rest',cert_t:'Decreto 176/2019: sanitary inspection certificate; no equipment rules.',proc_t:'Silent.',inst_t:'None.',path:'Keep the certificate in the inspection file; anchor to WHO values.'},
 {id:'ECU',name:'Ecuador',region:'Latin America',rk:'latam',gate:'none',cert:'none',process:'silent',fcMin:null,fcMax:null,ph:'—',ahj:'ARCSA',conf:'inferred',card:'latam-rest',cert_t:'Annual permiso de funcionamiento; no national pool water norm.',proc_t:'Silent.',inst_t:'None.',path:'Disclose at permit renewal.'},
 {id:'GTM',name:'Guatemala',region:'Latin America',rk:'latam',gate:'none',cert:'none',process:'silent',fcMin:null,fcMax:null,ph:'—',ahj:'MSPAS Área de Salud',conf:'verified',card:'latam-rest',cert_t:'Código de Salud Art. 101: MSPAS opinion for pool construction and operation; no specific regulation.',proc_t:'Silent.',inst_t:'None for equipment.',path:'Inform at licencia sanitaria renewal.'}
];

// Sub-national records
var SUBS = {
 usa:[
  {id:'CA',name:'California',gate:'approve',cert:'req',process:'clause',fcMin:1.0,ph:'7.2–8.0',ahj:'County Environmental Health',t:'CBC Ch. 31B §3123B.2 names "supplemental equipment" under NSF/ANSI 50; §3103B.1 plan review before altering equipment.',card:'us-ca'},
  {id:'FL',name:'Florida',gate:'notify',cert:'req',process:'silent',fcMin:1.0,ph:'7.0–7.8',ahj:'Local building dept + DOH',t:'FBC §454.1.6.5.1 NSF/ANSI 50; §454.1.6.5.6 NSF-pw pipe marking; DOH plan review repealed 2016.',card:'us-fl',trig:'NSF-pw marking required on recirculation plastics.'},
  {id:'TX',name:'Texas',gate:'notify',cert:'req',process:'clause',fcMin:1.0,ph:'7.2–7.8',ahj:'DSHS + local authority',t:'25 TAC §265.189: avoid "supplemental treatment system" classification (would demand EPA/FIFRA registration).',card:'us-tx',trig:'EPA/FIFRA registration if DSHS classes it a supplemental treatment system.'},
  {id:'NY',name:'New York',gate:'notify',cert:'req',process:'silent',fcMin:0.6,ph:'≤7.8',ahj:'County health department',t:'10 NYCRR 6-1.29 item 9.1 accepts NSF "or another testing laboratory"; names water-conditioning equipment.',card:'us-ny'},
  {id:'NV',name:'Nevada',gate:'approve',cert:'req',process:'silent',fcMin:1.0,ph:'7.2–7.8',ahj:'SNHD / Washoe',t:'Clark County code §309.2 NSF 50; SNHD reviews equipment alterations.',card:'us-nv'},
  {id:'AZ',name:'Arizona',gate:'notify',cert:'req',process:'clause',fcMin:1.0,ph:'7.2–7.8',ahj:'County (Maricopa, Pima)',t:'Maricopa Ch. VI Sec. 4 Reg. 3(c) ANSI/NSF 50.',card:'us-az'},
  {id:'HI',name:'Hawaii',gate:'notify',cert:'none',process:'clause',fcMin:0.6,ph:'7.2–7.8',ahj:'State DOH Sanitation Branch',t:'HAR 11-10 has no NSF reference; renovation plans to the Director.',card:'us-hi'},
  {id:'IL',name:'Illinois',gate:'approve',cert:'req',process:'silent',fcMin:1.0,ph:'7.2–7.6',ahj:'IDPH',t:'77 IAC 820.210 NSF 50 by an ANSI-accredited agency; "major alteration" permit via prequalified PE.',card:'us-il'},
  {id:'GA',name:'Georgia',gate:'approve',cert:'req',process:'clause',fcMin:1.0,ph:'7.2–7.8',ahj:'County Board of Health',t:'Rule 511-3-5-.04(9)(c) NSF 50 with engineer letter; 30-day plan submittal.',card:'us-ga'},
  {id:'CO',name:'Colorado',gate:'approve',cert:'req',process:'clause',fcMin:0.25,ph:'7.2–8.0',ahj:'CDPHE / county',t:'5 CCR 1003-5 "standards of the NSF"; 30-day Article II submittal.',card:'us-co'},
  {id:'WA',name:'Washington',gate:'approve',cert:'req',process:'silent',fcMin:1.5,ph:'7.2–8.0',ahj:'Local health officer',t:'WAC 246-260-021 construction permit for alteration; highest FC floor.',card:'us-wa'},
  {id:'AL',name:'Alabama',gate:'approve',cert:'req',process:'clause',fcMin:1.0,ph:'7.2–7.8',ahj:'County health departments (7 of 67 counties regulate; no state program)',t:'No statewide code. Baldwin County §2.2: permit and plan approval before changes to equipment on an existing pool; §5.C circulation equipment per NSF 50; other counties (Jefferson, Shelby, Mobile, Madison) have their own texts.',card:'us-al'},
  {id:'AK',name:'Alaska',gate:'none',cert:'advised',process:'clause',fcMin:0.3,ph:'—',ahj:'Alaska DEC Environmental Health (Anchorage enforces AMC 16.15)',t:'18 AAC 30.950: plan review only when constructed or extensively remodeled (≥25% of taxable value). NSF 50 cited only for DE filters. 30.540(c) non-chlorine disinfectants by waiver. 30.550(g) free chlorine to give HOCl yield ≥0.3 mg/L.',card:'us-ak'},
  {id:'AR',name:'Arkansas',gate:'approve',cert:'req',process:'clause',fcMin:1.0,ph:'7.0–7.8',ahj:'Arkansas Department of Health, Plan Review',t:'Rules Pertaining to Swimming Pools (2012) §V.A: plans to ADH before any alteration; alteration includes replacing any portion of the recirculation system. §IX.A: all system components meet NSF Standard 50. App. B: FC 1.0–5.0, pH 7.0–7.8.',card:'us-ar',trig:'§XXV: any "alternative equipment, product or material" needs ADH written acceptance (submit NSF data and cut sheets), regardless of disinfection status.'},
  {id:'CT',name:'Connecticut',gate:'approve',cert:'req',process:'clause',fcMin:0.8,ph:'7.2–7.8',ahj:'CT Dept. of Public Health (plan approval); local director of health',t:'Conn. Agencies Regs. §19-13-B33b(b)(1): no substantial alteration without commissioner-approved sealed plans; (b)(5) chemical feeders NSF; FC ≥0.8 (≥1.5 with CYA); other methods only if demonstrated to the commissioner; (b)(6) pH 7.2–7.8.',card:'us-ct'},
  {id:'DE',name:'Delaware',gate:'approve',cert:'req',process:'clause',fcMin:1.0,ph:'7.2–7.8',ahj:'DE Division of Public Health, Office of Engineering',t:'16 Del. Admin. Code 4464 §3.4.1: Approval to Construct before installing or altering pool equipment; §3.4.1.10 and §7.1.1 NSF listing required; §8.6.10 secondary systems NSF 50; §8.6.8.1 FAC ≥1.0 (2.0 with CYA); §8.5.1.1 pH 7.2–7.8.',card:'us-de'},
  {id:'DC',name:'District of Columbia',gate:'approve',cert:'req',process:'closed',fcMin:1.0,ph:'7.2–7.8',ahj:'DC Health (plan review, licence); DOB building permit',t:'25-C DCMR (MAHC 2nd ed. adopted): "alteration" expressly includes equipment changes and changes in recirculation or treatment systems; §706.1 plans to DC Health 30 days before retrofit; §408.2 treatment equipment NSF/ANSI 50; §404.2 FAC 1–10, pH 7.2–7.8.',card:'us-dc'},
  {id:'ID',name:'Idaho',gate:'none',cert:'none',process:'silent',fcMin:null,ph:'—',ahj:'City or county ordinance only (some district health departments by contract)',t:'No state rule since 1 July 2025: HB 202 (2025) removed DHW authority over public pool standards and IDAPA 16.02.14 lapsed; district health inspections stopped. Many local ordinances re-adopt the old IDAPA text (district plan approval for alteration, no NSF clause).',card:'us-id'},
  {id:'IN',name:'Indiana',gate:'approve',cert:'req',process:'clause',fcMin:1.0,ph:'7.2–7.8',ahj:'Indiana Dept. of Homeland Security (design release) + IDOH / local health dept.',t:'675 IAC 20-2-1: IDHS design release before construction, rehabilitation or alteration; 675 IAC 20-2-17: circulation equipment within NSF/ANSI 50 scope must conform and bear the seal; 410 IAC 6-2.1-30: FC 1.0–7.0, pH 7.2–7.8, alternative disinfectants only if accepted.',card:'us-in'},
  {id:'IA',name:'Iowa',gate:'approve',cert:'req',process:'silent',fcMin:1.0,ph:'7.2–7.8',ahj:'Iowa HHS Swimming Pool & Spa Program; local inspection agents',t:'641 IAC 15.5(1): department permit before a pool is constructed or reconstructed; 15.5(2)(a) engineered plans may be waived for feeder or simple pump/filter swaps; 15.5(5)–(12) pumps, filters, skimmers, feeders NSF 50 listed; 15.4(2) FC 1.0–8.0, pH 7.2–7.8.',card:'us-ia'},
  {id:'KS',name:'Kansas',gate:'none',cert:'none',process:'silent',fcMin:null,ph:'—',ahj:'City or county health departments (KDHE has no public pool program)',t:'KDHE Recreational Water Guidelines: no statewide rules for construction, operation, filtration or disinfection of public pools and no operator licensing; local ordinances only (Johnson County Aquatic Health Code 2025, Sedgwick, Wyandotte).',card:'us-ks',trig:'Johnson County asks operators to notify its Environment Division of any change to the pool or pumps; other counties vary and some have no code at all.'},
  {id:'KY',name:'Kentucky',gate:'approve',cert:'req',process:'clause',fcMin:1.0,ph:'7.2–7.8',ahj:'KY Dept. for Public Health (plan review); local health depts.',t:'902 KAR 10:123 §2(1): no alteration or reconstruction without written plan approval; §2(12) a change in equipment needs written cabinet approval; §7(1)(c) "all pool equipment systems shall be certified to NSF or ANSI 50 standards"; 902 KAR 10:120 FC 1–5, pH 7.2–7.8.',card:'us-ky'},
  {id:'LA',name:'Louisiana',gate:'approve',cert:'req',process:'clause',fcMin:0.4,ph:'7.2–7.8',ahj:'Louisiana Dept. of Health, state health officer',t:'LAC 51:XXIV.103: no major alteration to an existing pool without prior written approval of the state health officer; §501 circulation equipment per NSF Standard 50; §903.B innovative disinfection at the officer\'s discretion; §905 FC 0.4–0.6 in the current text (operators commonly maintain 1–3), pH 7.2–7.8.',card:'us-la'},
  {id:'ME',name:'Maine',gate:'approve',cert:'advised',process:'closed',fcMin:1.0,ph:'7.2–7.8',ahj:'Maine CDC Health Inspection Program (state)',t:'10-144 CMR Ch. 202 §2(B)(1): no changes to an existing pool or its appurtenances until plans are approved by the Department; §3(C) water sanitized by an Appendix A sanitizer (Cl 1.0–3.0, max 4.0); NSF 50 enters only via the incorporated ANSI/NSPI-1 design standard.',card:'us-me'},
  {id:'MD',name:'Maryland',gate:'approve',cert:'req',process:'closed',fcMin:1.5,ph:'7.2–7.8',ahj:'County health officer (delegated by MD Dept. of Health)',t:'COMAR 10.17.01.06: construction permit before altering a pool; .05B(1) "alter" includes adding a component not in the original system; .26A circulation components incl. "other pool and spa equipment" per ANSI/NSF 50, .26B any ANSI-accredited certifier accepted; .44A Cl 1.5–10; .45A pH 7.2–7.8.',card:'us-md'},
  {id:'MA',name:'Massachusetts',gate:'approve',cert:'advised',process:'clause',fcMin:1.0,ph:'7.2–7.8',ahj:'Local Board of Health (MA DPH sets the code)',t:'105 CMR 435.02(1): written Board of Health approval of PE-stamped plans before any change that may affect compliance of an existing pool; 435.06(3) NSF cited for filter rates only; 435.29 Cl 1.0–3.0, pH 7.2–7.8; other EPA-registered disinfectants only with BOH approval.',card:'us-ma'},
  {id:'MI',name:'Michigan',gate:'approve',cert:'none',process:'clause',fcMin:1.0,ph:'7.2–8.0',ahj:'EGLE Drinking Water & Environmental Health Division',t:'R 325.2113: construction permit for any "modification" of an existing pool regardless of cost (PE seal above $15,000); no NSF requirement for filters or feeders; R 325.2156 covers chemicals only; Table 3 FC ≥1 at pH 7.2–7.5, ≥2 at pH 7.5–8.0.',card:'us-mi'},
  {id:'MN',name:'Minnesota',gate:'approve',cert:'req',process:'closed',fcMin:1.0,ph:'7.2–7.8',ahj:'Minnesota Dept. of Health (commissioner)',t:'Minn. R. 4717.0450: no public pool constructed, installed or materially altered until plans are approved by the commissioner; 4717.2570 equipment installed in or altering a recirculation system must meet NSF 50; 4717.1750 chlorine, bromine or other halogens, FC 1.0–10, pH 7.2–7.8.',card:'us-mn'},
  {id:'MS',name:'Mississippi',gate:'none',cert:'none',process:'silent',fcMin:1.0,ph:'7.2–7.8',ahj:'None at state level; local building officials where ISPSC adopted',t:'MSDH guideline: "The Mississippi State Department of Health does not regulate swimming pools and spas. No permits are required"; recommendations only (FC 1–3, pH 7.2–7.8), with the CDC MAHC linked as guidance.',card:'us-ms'},
  {id:'MO',name:'Missouri',gate:'approve',cert:'none',process:'clause',fcMin:1.0,ph:'7.2–7.8',ahj:'Missouri DHSS on paper; county and city health departments enforce',t:'19 CSR 20-3.020(4): written DHSS approval of plans before alterations, changes or additions to an existing public bathing place; no equipment standard; 19 CSR 20-3.050 (lodging pools) FC ≥1.0, pH 7.2–7.8, alternative disinfectants by approval. Local codes (St. Louis County, Kansas City) govern in practice.',card:'us-mo'},
  {id:'MT',name:'Montana',gate:'approve',cert:'req',process:'clause',fcMin:1.0,ph:'7.2–7.8',ahj:'MT DPHHS Food & Consumer Safety + local building official',t:'ARM 37.115 with DPHHS Circular FCS 3-2022 (adopts ISPSC): §3.1.1(b) plans to DPHHS 30 days before installing equipment "not identical or substantially similar or new to the design"; ISPSC §309.2 NSF 50; Table 2 FC 1–10 (2–10 stabilized), pH 7.2–7.8.',card:'us-mt',trig:'Circular §2.3.2: any secondary or supplemental disinfection system must be NSF-approved and department-approved; captures the device only if classed as supplemental disinfection.'},
  {id:'NE',name:'Nebraska',gate:'approve',cert:'req',process:'clause',fcMin:2.0,ph:'7.2–7.8',ahj:'Nebraska DWEE Swimming Pool Program, Engineering Section',t:'178 NAC 2-003: written Department approval of plans before construction, modification or improvement; 003.03 exempts only like-for-like replacements; 2-005.11(A) recirculation components certified to ANSI/NSF 50; 2-007.02 FC ≥2.0 as published, close above 10, pH 7.2–7.8.',card:'us-ne'},
  {id:'NH',name:'New Hampshire',gate:'approve',cert:'req',process:'closed',fcMin:1.0,ph:'7.0–7.8',ahj:'NH Dept. of Environmental Services, Public Bathing Facility program',t:'Env-Wq 1103.01(a): prior NHDES approval of construction, design and physical specifications; 1105.22(a) any component installed after 2014 certified by NSF "or a comparable independent testing organization" to NSF/ANSI 50; 1106.08(b) enumerated disinfection methods; 1105.13 FAC 1–5, pH 7.0–7.8.',card:'us-nh'},
  {id:'NJ',name:'New Jersey',gate:'approve',cert:'none',process:'clause',fcMin:1.0,ph:'7.2–7.8',ahj:'Local health authority + local construction code official (NJDOH oversight)',t:'N.J.A.C. 8:26-2.3: written approval of the local health authority before any alteration; 8:26-1.3 "alter" means any modification of equipment or change of water-flow pattern (normal maintenance and like-for-like excluded); no NSF 50 language; App. C Cl 1.0–10, pH 7.2–7.8.',card:'us-nj'},
  {id:'NM',name:'New Mexico',gate:'notify',cert:'req',process:'clause',fcMin:1.0,ph:'7.2–7.8',ahj:'NMED Environmental Health Bureau Aquatics Program (Albuquerque/Bernalillo separate)',t:'7.18.1 NMAC adopts the CDC MAHC 1st ed. by reference; 7.18.1.12.J non-substantial alteration needs no permit but the owner "shall contact the department to review proposed changes prior to starting"; MAHC §5.7.3 FC 1–10, pH 7.2–7.8.',card:'us-nm',conf:'secondary',trig:'MAHC §4.7.3.4 as adopted: supplemental treatment systems must be NSF/ANSI 50 listed; the IAPMO listing satisfies this if the device is classed as supplemental.'},
  {id:'NC',name:'North Carolina',gate:'approve',cert:'req',process:'clause',fcMin:1.0,ph:'7.2–7.8',ahj:'NC DHHS Environmental Health Section via local health department',t:'15A NCAC 18A .2537(b): equipment replacement must comply with .2514–.2534 and be approved by the Department prior to installation (repairs exempt); .2518/.2519/.2530 pumps, filters, skimmers, feeders NSF/ANSI 50; .2535 FC ≥1, pH 7.2–7.8, disinfection by EPA-registered process.',card:'us-nc'},
  {id:'ND',name:'North Dakota',gate:'none',cert:'none',process:'clause',fcMin:1.0,ph:'—',ahj:'ND HHS (minimal) + local public health units and city building officials',t:'NDAC 33-29-01 (1985, skeletal): 33-29-01-07 disinfection by continuous chlorination "or other means of equal bactericidal efficiency", FC ≥1 mg/L at all times; no NSF, plan-approval or alteration language; 33-29-01-12 stricter local ordinances (e.g. Bismarck) control.',card:'us-nd'},
  {id:'OH',name:'Ohio',gate:'approve',cert:'req',process:'clause',fcMin:1.0,ph:'7.2–7.8',ahj:'Ohio Dept. of Health / local licensor health district',t:'OAC 3701-31-05(A): no substantial alteration until plans approved by the director; (C) substantial alteration includes changes affecting circulation systems (like-for-like within 10% exempt); 3701-31-05.1(F)(12)(e) skimmers, filters, feeders NSF-listed; 3701-31-04(D)(4) secondary disinfection needs approval; FC ≥1.0, pH 7.2–7.8.',card:'us-oh'},
  {id:'OK',name:'Oklahoma',gate:'notify',cert:'req',process:'clause',fcMin:1.0,ph:'7.2–7.8',ahj:'Oklahoma State Dept. of Health, Consumer Health Service (Tulsa and OKC-County locally)',t:'OAC 310:315-3-1(b): minor changes or additions to an existing bathing place need a written scope of work to the Department (informal review); major remodel needs PE-sealed plans. 310:315-7-16 feeders NSF-listed, 7-14(l) skimmers NSF 50; 310:320 FC 1–5, pH 7.2–7.8.',card:'us-ok'},
  {id:'OR',name:'Oregon',gate:'notify',cert:'req',process:'clause',fcMin:1.0,ph:'7.0–7.8',ahj:'OHA Public Health Division or county Local Public Health Authority',t:'OAR 333-060-1000 and 333-062-1000 (MAHC-based, eff. 1 Apr 2025): §4.1.3.2.1 for a non-substantial alteration the owner "shall contact the AHJ to review proposed changes prior to starting"; §4.1.3.3 replacement equipment needs written equivalency approval; §5.7.3.1.1.2 FC 1.0 (2.0 with CYA)–10, pH 7.0–7.8.',card:'us-or',trig:'§5.7.3.3: supplemental treatment must be NSF/ANSI 50 listed and EPA-registered if a pesticide, and must not modify chlorine or pH requirements; satisfied if never marketed as a pesticide.'},
  {id:'PA',name:'Pennsylvania',gate:'approve',cert:'none',process:'clause',fcMin:0.4,ph:'7.2–8.2',ahj:'PA Dept. of Health Bathing Place program; county/municipal health depts. issue local permits',t:'28 Pa. Code §18.7: written DOH approval before deviating from approved plans; §18.15 additions and alterations only on permit; §18.29 Cl ≥0.4, pH 7.2–8.2, other disinfecting methods only after approval; no NSF language; construction via UCC (ISPSC 2018).',card:'us-pa',trig:'§18.7: "a treatment process or protective measure may not be added to, altered or discontinued without securing appropriate approval"; position the device as a certified circulation component, never as water treatment.'},
  {id:'RI',name:'Rhode Island',gate:'approve',cert:'req',process:'clause',fcMin:1.0,ph:'7.2–7.8',ahj:'RI Dept. of Health, Licensed Swimming Pools Program',t:'216-RICR-50-05-4 §4.1.3 incorporates the 2018 MAHC and NSF/ANSI 50; §4.4(B) no construction or alteration without RIDOH preliminary approval, and any change to water treatment or hydraulics is a "substantial alteration" regardless of cost; §4.6.2(B)(7) Cl 1.0–10, pH 7.2–7.8.',card:'us-ri'},
  {id:'SC',name:'South Carolina',gate:'approve',cert:'req',process:'clause',fcMin:1.0,ph:'7.0–7.8',ahj:'SC Dept. of Environmental Services, Recreational Waters',t:'R.61-51 B.2: no pool constructed or altered until a permit to construct is issued; A.1 "alteration" is any change in equipment; B.5(b) Change Order Request for existing pools; C.33 equipment approved by NSF "or other laboratories acceptable to the Department"; J.14(b) FC 1–8, pH 7.0–7.8.',card:'us-sc',trig:'C.21: "supplemental water treatment systems may be approved on a case by case basis"; expect SCDES to want a change order and the IAPMO listing.'},
  {id:'SD',name:'South Dakota',gate:'approve',cert:'req',process:'clause',fcMin:0.5,ph:'7.2–7.8',ahj:'SD Dept. of Health, Office of Health Protection (lodging, resort and campground pools)',t:'ARSD 44:02:02:22, 44:02:05:15, 44:02:14:11 incorporate the 1996 GLUMRB pool standards: §2.1.3 plans for modifications to the reviewing authority; §9.0.1 recirculation components per NSF/ANSI 50; FC ≥0.5 at pH 7.2 (≥1.0 with cyanurate). Municipal pools not tied to lodging are unregulated at state level.',card:'us-sd'},
  {id:'TN',name:'Tennessee',gate:'approve',cert:'req',process:'clause',fcMin:0.5,ph:'7.2–7.6',ahj:'TN Dept. of Health, Environmental Health; county health depts. inspect',t:'Tenn. Comp. R. 1200-23-05-.03(2)(a): no alteration or reconstruction without plan approval; .01 "alter" includes installing or removing equipment; .03(n)(6) filters per NSF (NSF 50 not named for other gear); .02(4)(c) FC 0.5–3.0, pH 7.2–7.6, other methods if demonstrated.',card:'us-tn'},
  {id:'UT',name:'Utah',gate:'approve',cert:'req',process:'clause',fcMin:1.0,ph:'7.2–7.8',ahj:'Local health department / local health officer',t:'R392-302-5(1): plans to the LHD for "a modification project of an existing pool, or replacement of equipment that is different from that originally approved"; the LHO may exempt if no adverse effect. R392-302-19/-23/-24 circulation equipment, filters, feeders NSF/ANSI 50; -25 FC 1.0 (2.0 stabilized)–10, pH 7.2–7.8.',card:'us-ut'},
  {id:'VT',name:'Vermont',gate:'none',cert:'none',process:'clause',fcMin:1.0,ph:'7.0–8.0',ahj:'Vermont Dept. of Health Food & Lodging Program (lodging pools only)',t:'No statewide public-pool code; only pools at licensed lodging are regulated (Licensed Lodging Establishment Rule §18). §5.3 plan review only before new construction or significant renovation; §18.5.1.1 FAC 1.0–5.0; §18.5.2 pH 7.0–8.0; §18.5.1.3 non-chlorine disinfection must be shown equivalent.',card:'us-vt'},
  {id:'VA',name:'Virginia',gate:'approve',cert:'req',process:'clause',fcMin:0.5,ph:'≥7.2',ahj:'VDH via local health dept. (tourist pools); local building official under USBC/ISPSC',t:'12VAC5-460-30(A): pools opened after remodeling or major alteration need plans to the local health dept. and written Commissioner approval; -250 chlorine feeders required, other methods by approval; -280 FC ≥0.5; -290 pH ≥7.2. NSF 50 via USBC/ISPSC §§302.3, 309.2 (listed and labeled).',card:'us-va'},
  {id:'WV',name:'West Virginia',gate:'approve',cert:'advised',process:'clause',fcMin:1.0,ph:'7.2–7.8',ahj:'WV Bureau for Public Health (Commissioner); local health depts. inspect',t:'64CSR16 §3.1: no person may establish, construct or renovate a facility without a construction permit (four plan sets 45 days ahead); §6.1 incorporates ANSI/NSPI-1 2003 (NSF 50 indirectly); §7.1.d FC 1–5; §7.4.a pH 7.2–7.8; §7.1.f other disinfectants need approval and EPA registration.',card:'us-wv'},
  {id:'WI',name:'Wisconsin',gate:'approve',cert:'req',process:'clause',fcMin:1.0,ph:'7.2–7.8',ahj:'Wisconsin DSPS (plan approval, SPS 390) + DATCP (licence)',t:'ATCP 76.04(2): operator submits pool modification plans to DSPS under SPS 390, which requires written approval of all changes prior to installation; ATCP 76.15 chlorine generators, UV and pathogen-inactivating technologies NSF 50; Table A FC ≥1.0 (2.0 with stabilizer), max 10, pH 7.2–7.8.',card:'us-wi',trig:'ATCP 76.15(4): technologies that "inactivate or kill pathogens" must be NSF 50 certified and EPA-registered; captures the device only if marketed as pathogen-killing.'},
  {id:'WY',name:'Wyoming',gate:'notify',cert:'req',process:'clause',fcMin:1.0,ph:'7.0–7.8',ahj:'Wyoming Dept. of Agriculture, Consumer Health Services',t:'WDA Rules for Public Swimming Pools Ch. 2 §5(a)(iii): plans before remodeling only "if the regulatory authority determines that plans and specifications are necessary"; Ch. 3 pumps and filters per NSF-50; Ch. 5 §1 FC 1.0–8.0 (ideal 2–3), pH 7.0–7.8.',card:'us-wy',trig:'Ch. 4 §5: an "ancillary non-chlorine sanitizer" must be EPA-registered and used with chlorine or bromine; captures only a device marketed as a sanitizer.'}
 ],
 can:[
  {id:'ON',name:'Ontario',gate:'approve',cert:'none',fcMin:0.5,ph:'7.2–7.8',ahj:'Public Health Inspector + building dept',t:'Reg. 565 s.5: building permit number, 14-day notice, written reopening permission.',card:'ca-on'},
  {id:'BC',name:'British Columbia',gate:'approve',cert:'none',fcMin:0.5,ph:'7.2–7.8',ahj:'Regional health authority',t:'Reg. 296/2010 s.5: construction permit or s.5(6) minor-alteration waiver.',card:'ca-bc'},
  {id:'AB',name:'Alberta',gate:'approve',cert:'none',fcMin:1.0,ph:'6.8–7.6',ahj:'Alberta Health Services',t:'AR 204/2014 s.8(1)(b): written approval before altering the hydraulic system (form 19381).',card:'ca-ab'},
  {id:'QC',name:'Quebec',gate:'none',cert:'none',fcMin:0.5,ph:'7.0–7.8',ahj:'MELCCFP',t:'Q-2, r. 39: no pre-approval; French documentation; 2.0 mg/L maximum.',card:'ca-qc'}
 ],
 aus:[
  {id:'NSW',name:'New South Wales',gate:'none',cert:'none',fcMin:1.0,ph:'7.0–7.8',ahj:'Local council',t:'NSW Health is not an approval authority; adjuncts welcomed.',card:'au-nsw'},
  {id:'QLD',name:'Queensland',gate:'none',cert:'none',fcMin:1.0,ph:'7.2–7.8',ahj:'Local council',t:'No state law on pool water quality; council local laws may adopt the guideline.',card:'au-qld'},
  {id:'VIC',name:'Victoria',gate:'none',cert:'none',fcMin:1.0,ph:'7.2–7.8',ahj:'Local council',t:'Hotel pools are Category 2; update the WQRMP.',card:'au-vic'},
  {id:'WA',name:'Western Australia',gate:'notify',cert:'none',fcMin:1.0,ph:'7.2–7.8',ahj:'WA Health Water Unit',t:'The treatment plant is CHO-approved by classification; WA Health is written to before installation to confirm it is not an alteration requiring re-approval.',card:'au-wa'}
 ],
 uae:[
  {id:'DXB',name:'Dubai',gate:'approve',cert:'none',fcMin:1.0,ph:'7.2–7.6',ahj:'DM Health & Safety / Trakhees',t:'GU81 §4-4: no alteration without DM approval; hazard assessment.',card:'ae-dxb'},
  {id:'AUH',name:'Abu Dhabi',gate:'approve',cert:'none',fcMin:1.0,ph:'7.2–7.6',ahj:'Municipality Public Health',t:'Law 2/2012 regs §4(1): no modifications without licence amendment.',card:'ae-auh'}
 ]
};

var LABELS = {
 gate:{none:'None needed',notify:'Notify authority',approve:'Approval required'},
 cert:{req:'NSF 50 required',none:'No certification required',advised:'Advised or indirect'},
 process:{closed:'Closed process list',clause:'Approved-disinfectant clause',silent:'Silent on passive devices'},
 conf:{verified:'Verified in primary text',secondary:'Secondary source',inferred:'Inferred'}
};
var VIEWS = {
 gate:{title:'Permission to install: what must happen before the device goes in',keys:['none','notify','approve'],vars:{none:'--g-none',notify:'--g-notify',approve:'--g-approve'},desc:{none:'None needed: install and log',notify:'Notify the authority in writing',approve:'Approval, permit or plan review required'}},
 cert:{title:'Product certification: is NSF/ANSI 50 required by law?',keys:['req','advised','none'],vars:{req:'--c-req',advised:'--c-advised',none:'--c-none'},desc:{req:'NSF 50 required by the code; the IAPMO certificate satisfies it',advised:'Not named in law; reached indirectly or a local mark smooths acceptance',none:'No certification required'}},
 process:{title:'Process rules: does the law restrict treatment methods?',keys:['closed','clause','silent'],vars:{closed:'--p-closed',clause:'--p-clause',silent:'--p-silent'},desc:{closed:'Enumerated permitted processes; opinion needed',clause:'Alternative disinfectants need approval; device is outside',silent:'No rule touches a passive device'}},
 fc:{title:'Free-chlorine floor the pool must still hold (mg/L)',keys:['fc0','fc1','fc2','fc3','fcna'],vars:{fc0:'--fc0',fc1:'--fc1',fc2:'--fc2',fc3:'--fc3',fcna:'--land-nr'},desc:{fc0:'≤ 0.3',fc1:'0.4 – 0.5',fc2:'0.6 – 0.9',fc3:'≥ 1.0',fcna:'No national value'}},
 conf:{title:'Evidence grade behind each record',keys:['verified','secondary','inferred'],vars:{verified:'--k-ver',secondary:'--k-sec',inferred:'--k-inf'},desc:{verified:'Primary legislation or authority guidance read',secondary:'Reputable summary',inferred:'Reasoned from the framework'}}
};
var REGIONS = {world:null,na:[-170,8,-50,74],carib:[-92,8,-58,28],eu:[-12,34,46,72],me:[24,10,66,44],af:[-20,-36,58,38],apac:[60,-48,180,56],latam:[-96,-58,-30,26]};

/* ===================== STATE ===================== */
var TITLES = {gate:'Permission to install: what must happen before the device goes in',cert:'Product certification: is NSF/ANSI 50 required by law?',process:'Process rules: does the law restrict treatment methods?',fc:'Chlorine floor: the free-chlorine minimum the pool must still hold (mg/L)',conf:'Evidence: the source basis behind each record'};
var state={view:'gate',level:'world',region:'world',sel:null,q:'',filter:null};
var map=null, zoom=null, tk={k:1,x:0,y:0};
var byId={}; J.forEach(function(j){byId[j.id]=j});
var USAB={}; SUBS.usa.forEach(function(s){USAB[s.id]=s});
var $=function(id){return document.getElementById(id)};

function cssv(n){return getComputedStyle(document.getElementById('arcm')).getPropertyValue(n).trim()}
function fcKey(v){ if(v==null) return 'fcna'; if(v<=0.3) return 'fc0'; if(v<=0.5) return 'fc1'; if(v<0.95) return 'fc2'; return 'fc3'; }
function rawKey(j){ if(state.view==='fc') return fcKey(j.fcMin); if(state.view==='conf') return j.conf||'verified'; return j[state.view]||'silent'; }
function keyFor(j){ return state.view+'_'+rawKey(j); }
function fills(){
  var f={defaultFill:cssv('--land-nr')};
  Object.keys(VIEWS).forEach(function(v){ var V=VIEWS[v]; V.keys.forEach(function(k){ f[v+'_'+k]=cssv(V.vars[k]); }); });
  return f;
}
function fmtFC(j){ if(j.fcMin==null) return '—'; return j.fcMin + (j.fcMax!=null ? '–'+j.fcMax : '+') + ' mg/L'; }
function esc(s){return String(s).replace(/&/g,'&amp;').replace(/</g,'&lt;')}
function labelOf(key){ return state.view==='fc' ? VIEWS.fc.desc[key] : (LABELS[state.view]||{})[key] || key; }
function pool(){ return state.level==='usa' ? SUBS.usa : J; }
function matches(j,q){ return (j.name+' '+(j.region||'')+' '+j.ahj+' '+(j.id||'')).toLowerCase().indexOf(q)>-1; }
function isDim(j){
  var q=state.q.toLowerCase();
  if(!j) return !!(state.filter||q);
  if(q && !matches(j,q)) return true;
  if(state.filter && rawKey(j)!==state.filter) return true;
  return false;
}

/* ===================== MAP ===================== */
var tip=null, vb={w:1000,h:400};
function buildMap(){
  var el=$('map'); el.innerHTML='';
  el.classList.toggle('usa', state.level==='usa');
  var usa = state.level==='usa';
  var data={};
  pool().forEach(function(j){ data[j.id]={fillKey:keyFor(j)}; });
  map=new Datamap({
    element:el, scope: usa?'usa':'world', responsive:false, fills:fills(), data:data,
    setProjection: usa? undefined : function(element){
      var w=element.offsetWidth, h=element.offsetHeight;
      var s=w/(2*Math.PI);
      var projection=d3.geo.equirectangular().scale(s).translate([w/2, h/2 + s*0.227]);
      return {path:d3.geo.path().projection(projection), projection:projection};
    },
    geographyConfig:{
      borderColor:cssv('--border'), borderWidth:0.6,
      highlightFillColor:function(d){ var F=fills(); return (d&&d.fillKey&&F[d.fillKey])||F.defaultFill; },
      highlightBorderColor:cssv('--select'), highlightBorderWidth:1.6,
      popupOnHover:false
    },
    bubblesConfig:{borderWidth:1.2, borderColor:cssv('--surface'), fillOpacity:1, highlightFillOpacity:1,
      highlightFillColor:function(d){ var F=fills(); return (d&&d.fillKey&&F[d.fillKey])||F.defaultFill; },
      highlightBorderColor:cssv('--select'), highlightBorderWidth:2, popupOnHover:false},
    done:function(dm){
      vb={w:el.offsetWidth,h:el.offsetHeight};
      dm.svg.attr('viewBox','0 0 '+vb.w+' '+vb.h).attr('preserveAspectRatio','xMidYMid meet').attr('width',null).attr('height',null);
      if(!usa){ dm.bubbles(bubbleData()); }
      bindSelect(dm);
      tip=d3.select(el).append('div').attr('class','tip hoverinfo').attr('role','tooltip').style('display','none');
      bindTips(dm);
      var svg=dm.svg;
      zoom=d3.behavior.zoom().scaleExtent([1,14]).on('zoom',function(){ tk={k:d3.event.scale,x:d3.event.translate[0],y:d3.event.translate[1]}; applyT(false); });
      svg.call(zoom).on('dblclick.zoom',null);
      tk={k:1,x:0,y:0}; applyT(false);
      if(!usa && state.region!=='world') focusRegion(state.region,false);
      markSelected();
    }
  });
}
function bubbleData(){ return J.filter(function(j){return j.ll}).map(function(j){ return {jid:j.id,name:j.name,latitude:j.ll[0],longitude:j.ll[1],radius:5.5,fillKey:keyFor(j)}; }); }
/* Select on press-and-release within a small tolerance. The drag-to-pan behaviour cancels the
   browser's click event whenever the pointer moves at all between press and release, so a plain
   click handler misses many real clicks; this does not. Works for mouse and touch. */
var pressPt=null;
function bindSelect(M){
  var svg=M.svg, svgNode=svg.node();
  function pt(e){ return (e.changedTouches&&e.changedTouches[0])||(e.touches&&e.touches[0])||e; }
  /* Hit-test the release point: mouse events on an SVG are not always delivered to the shape itself. */
  function hit(x,y){
    /* A marker within 12px of the release point wins over the country under it. */
    var best=null, bestD=144;
    svg.selectAll('.datamaps-bubble').each(function(d){ var b=this.getBoundingClientRect(); var cx=b.left+b.width/2, cy=b.top+b.height/2; var dd=(cx-x)*(cx-x)+(cy-y)*(cy-y); if(dd<bestD){ bestD=dd; best=d.jid; } });
    if(best) return best;
    var el=document.elementFromPoint(x,y);
    while(el && el!==svgNode && el!==document.body){
      if(el.classList){
        if(el.classList.contains('datamaps-subunit')){ var g=d3.select(el).datum(); return g&&g.id; }
        if(el.classList.contains('datamaps-bubble')){ var b=d3.select(el).datum(); return b&&b.jid; }
      }
      el=el.parentNode;
    }
    return null;
  }
  function press(){ var p=pt(d3.event); pressPt={x:p.clientX,y:p.clientY}; }
  function release(){
    var e=d3.event, p=pt(e);
    if(!pressPt) return; var dx=p.clientX-pressPt.x, dy=p.clientY-pressPt.y; pressPt=null;
    if(dx*dx+dy*dy>64) return;
    var id=hit(p.clientX,p.clientY); if(!id) return;
    if(e.type==='touchend' && e.cancelable) e.preventDefault();
    select(id);
  }
  svg.on('mousedown.sel',press).on('touchstart.sel',press).on('mouseup.sel',release).on('touchend.sel',release);
}
function showTip(html){ if(!tip) return; tip.html(html).style('display','block'); }
function moveTip(){
  if(!tip) return; var el=$('map'); var p=d3.mouse(el); var W=el.offsetWidth;
  var flipX = p[0] > W*0.62, flipY = p[1] < 90;
  tip.style('left', p[0]+'px').style('top', p[1]+'px')
     .style('transform', 'translate('+(flipX?'calc(-100% - 14px)':'14px')+','+(flipY?'12px':'calc(-100% - 12px)')+')');
}
function hideTip(){ if(tip) tip.style('display','none'); }
function clearHover(){
  hideTip(); var M=map; if(!M) return;
  M.svg.selectAll('.datamaps-subunit').style('stroke',null).style('stroke-width',(0.6/tk.k)+'px');
  M.svg.selectAll('.datamaps-bubble').style('stroke',null).style('stroke-width',(1.2/tk.k)+'px');
}
function bindTips(m){
  var M = m || map; if(!M) return; var usa = state.level==='usa';
  d3.select($('map')).on('mouseleave.tip',clearHover);
  M.svg.on('mouseover.sea',function(){ var t=d3.event.target; if(t && t.tagName==='svg') clearHover(); });
  function resetOthers(me){
    M.svg.selectAll('.datamaps-subunit').filter(function(){return this!==me}).style('stroke',null).style('stroke-width',(0.6/tk.k)+'px');
    M.svg.selectAll('.datamaps-bubble').filter(function(){return this!==me}).style('stroke',null).style('stroke-width',(1.2/tk.k)+'px');
  }
  M.svg.selectAll('.datamaps-subunit')
    .on('mouseover.tip',function(geo){ resetOthers(this); var j = usa ? USAB[geo.id] : byId[geo.id]; showTip(j ? hoverHtml(j,usa) : '<b>'+esc(geo.properties.name)+'</b><span class="m">Not researched</span>'); moveTip(); })
    .on('mousemove.tip',moveTip)
    .on('mouseout.tip',hideTip);
  M.svg.selectAll('.datamaps-bubble')
    .on('mouseover.tip',function(d){ resetOthers(this); showTip(hoverHtml(byId[d.jid],false)); moveTip(); })
    .on('mousemove.tip',moveTip)
    .on('mouseout.tip',hideTip);
}
function applyT(anim){
  if(!map) return;
  var g=map.svg.selectAll('svg > g');
  var t='translate('+tk.x+','+tk.y+') scale('+tk.k+')';
  (anim && !window.matchMedia('(prefers-reduced-motion: reduce)').matches ? g.transition().duration(500) : g).attr('transform',t);
  map.svg.selectAll('.datamaps-subunit').style('stroke-width',(0.6/tk.k)+'px');
  map.svg.selectAll('.datamaps-bubble').attr('r', 5.5/Math.sqrt(tk.k)).style('stroke-width',(1.2/tk.k)+'px');
  if(zoom){ zoom.scale(tk.k).translate([tk.x,tk.y]); }
}
function focusRegion(rk,anim){
  var b=REGIONS[rk]; var W=vb.w, H=vb.h;
  if(!b || !map){ tk={k:1,x:0,y:0}; applyT(anim); return; }
  var p=map.projection; var a=p([b[0],b[3]]), c=p([b[2],b[1]]);
  var dx=c[0]-a[0], dy=c[1]-a[1];
  var k=Math.min(W/dx, H/dy)*0.92; k=Math.max(1,Math.min(14,k));
  var cx=(a[0]+c[0])/2, cy=(a[1]+c[1])/2;
  tk={k:k, x:W/2-cx*k, y:H/2-cy*k}; applyT(anim);
}
function zoomBy(f){ var W=vb.w,H=vb.h; var k2=Math.max(1,Math.min(14,tk.k*f)); var r=k2/tk.k; tk={k:k2,x:W/2-(W/2-tk.x)*r,y:H/2-(H/2-tk.y)*r}; applyT(true); }
function hoverHtml(j,usa){
  var key = rawKey(j);
  return '<b>'+esc(j.name)+'</b><span class="m">'+esc(labelOf(key))+'</span><br><span class="m">FC '+esc(fmtFC(j))+' · pH '+esc(j.ph)+'</span><br>'+esc(j.ahj)+(j.trig?'<br><span class="m">Conditional requirement · see record</span>':'')+'<br><span class="m" style="color:var(--ink-3)">Click '+(usa?'the state':(j.ll?'the marker':'the country'))+' to open its record</span>';
}
function recolor(){
  if(!map) return;
  var data={}; pool().forEach(function(j){ data[j.id]={fillKey:keyFor(j)}; });
  map.updateChoropleth(data);
  if(state.level==='world'){
    map.bubbles(bubbleData());
    bindSelect(map);
    bindTips();
    applyT(false);
  }
  markSelected();
}
function markSelected(){
  if(!map) return;
  var usa = state.level==='usa';
  map.svg.selectAll('.datamaps-subunit')
    .classed('selected',function(g){ return state.sel && g.id===state.sel; })
    .classed('dim',function(g){ return isDim(usa?USAB[g.id]:byId[g.id]); });
  map.svg.selectAll('.datamaps-bubble')
    .classed('selected',function(d){ return state.sel && d.jid===state.sel; })
    .classed('dim',function(d){ return isDim(byId[d.jid]); });
}
/* Pan the selected shape clear of the record drawer when the drawer overlays the map
   (window narrower than 1100px). On wider screens the layout makes room for the drawer instead. */
function ensureVisible(id){
  if(!map || window.innerWidth<=720 || window.innerWidth>=1100) return;
  var el=$('map'); var node = map.svg.select('.datamaps-subunit.'+id).node();
  if(!node){ map.svg.selectAll('.datamaps-bubble').each(function(d){ if(d.jid===id) node=this; }); }
  if(!node) return;
  var r=node.getBoundingClientRect(); var drawerLeft = window.innerWidth - Math.min(440, window.innerWidth);
  var limit = drawerLeft - 24;
  if(r.right > limit){
    var pxPerVb = el.offsetWidth / vb.w;
    tk.x -= (r.right - limit + 40) / pxPerVb; applyT(true);
  }
}

/* ===================== LEGEND / STATS / TABS ===================== */
function renderLegend(){
  var V=VIEWS[state.view], c=counts();
  var L=$('legend');
  L.innerHTML = V.keys.map(function(k){ return '<button type="button" class="lg" data-k="'+k+'" aria-pressed="'+(state.filter===k)+'"><span class="sw" style="background:'+cssv(V.vars[k])+'"></span>'+esc(V.desc[k])+'<span class="n">'+(c[k]||0)+'</span></button>'; }).join('')
    + (state.level==='world' ? '<span class="static"><span class="sw round" style="background:'+cssv('--ink-3')+'"></span>Marker = small territory</span>' : '')
    + '<span class="static"><span class="sw" style="background:'+cssv('--land-nr')+'"></span>Not researched</span>'
    + (state.filter ? '<button type="button" class="clear" id="clearf">Show all</button>' : '');
  L.querySelectorAll('.lg').forEach(function(b){ b.addEventListener('click',function(){ toggleFilter(b.dataset.k); }); });
  var cf=$('clearf'); if(cf) cf.addEventListener('click',function(){ toggleFilter(null); });
  $('maptitle').textContent = TITLES[state.view] + (state.level==='usa' ? ' (US states)' : '');
  $('listtitle').textContent = TITLES[state.view] + ' (table)';
  var S=$('stats'); var total=(state.level==='list'?J:pool()).length;
  S.innerHTML = '<div class="stat total"><div class="big">'+total+'</div><div class="w">'+(state.level==='usa'?'states and DC':(state.level==='list'?'jurisdictions in the table':'jurisdictions on the map'))+'</div></div>'
    + V.keys.filter(function(k){return c[k]}).map(function(k){ return '<button type="button" class="stat" data-k="'+k+'" aria-pressed="'+(state.filter===k)+'"><div class="big">'+c[k]+'</div><div class="w"><span class="sw" style="background:'+cssv(V.vars[k])+'"></span>'+esc(labelOf(k))+'</div></button>'; }).join('');
  S.querySelectorAll('.stat[data-k]').forEach(function(b){ b.addEventListener('click',function(){ toggleFilter(b.dataset.k); }); });
}
function toggleFilter(k){ state.filter = (k && state.filter!==k) ? k : null; markSelected(); renderLegend(); if(state.level==='list') renderTable(); }
function counts(){ var c={}; (state.level==='list' ? J : pool()).forEach(function(j){ var k=rawKey(j); c[k]=(c[k]||0)+1; }); return c; }
function setView(v){
  state.view=v; state.filter=null;
  document.querySelectorAll('#qtabs .qtab').forEach(function(b){ b.setAttribute('aria-selected', b.dataset.view===v ? 'true':'false'); });
  recolor(); renderLegend(); if(state.level==='list') renderTable(); renderPanel();
}

/* ===================== RECORD DRAWER ===================== */
function chip(kind,key){ var v=VIEWS[kind]; var lab=(LABELS[kind]||v.desc)[key]||key; return '<span class="chip" style="--dot:'+cssv(v.vars[key])+'">'+esc(lab)+'</span>'; }
function openDrawer(){ var P=$('panel'); P.classList.add('open'); P.setAttribute('aria-hidden','false'); P.scrollTop=0; var w=document.querySelector('.wrap'); if(w) w.classList.add('drawer-open'); }
function closeDrawer(){ var P=$('panel'); P.classList.remove('open'); P.setAttribute('aria-hidden','true'); var w=document.querySelector('.wrap'); if(w) w.classList.remove('drawer-open'); }
function renderPanel(){
  var P=$('panel');
  var j = state.sel ? (state.level==='usa' ? USAB[state.sel] : byId[state.sel]) : null;
  if(!j){ closeDrawer(); return; }
  var isSub = state.level==='usa';
  var head='<div class="ph"><div class="title"><div><h3>'+esc(j.name)+'</h3><div class="region">'+esc(isSub?'United States · state':j.region)+' · '+esc(j.ahj)+' · <span class="conf">'+esc((j.conf||'verified').toUpperCase())+'</span></div></div><button class="close" type="button" aria-label="Close record">×</button></div><div class="chips">'+chip('gate',j.gate)+chip('cert',j.cert||'req')+(j.process?chip('process',j.process):'')+(j.trig?'<span class="chip" style="--dot:var(--g-approve)">Conditional</span>':'')+'</div></div>';
  var wq='<span class="mono">FC '+esc(fmtFC(j))+' · pH '+esc(j.ph)+'</span>';
  var rows;
  if(isSub){
    rows='<div class="rows"><div class="k">Water</div><div class="v">'+wq+'</div><div class="k">Rule</div><div class="v">'+esc(j.t)+'</div>'+(j.trig?'<div class="k">Trigger</div><div class="v"><b>Conditional:</b> '+esc(j.trig)+'</div>':'')+'<div class="k path">Record</div><div class="v path"><a href="https://www.aquarevwater.us/compliancemap#'+j.card+'">Open the full record in the compliance map</a></div></div>';
  } else {
    rows='<div class="rows"><div class="k">Water</div><div class="v">'+wq+'</div><div class="k">Product</div><div class="v">'+esc(j.cert_t)+'</div><div class="k">Process</div><div class="v">'+esc(j.proc_t)+'</div>'+(j.trig?'<div class="k">Trigger</div><div class="v"><b>Conditional:</b> '+esc(j.trig)+'</div>':'')+'<div class="k">Install</div><div class="v">'+esc(j.inst_t)+'</div><div class="k path">In practice</div><div class="v path">'+esc(j.path)+'</div><div class="k">Source</div><div class="v"><a href="https://www.aquarevwater.us/compliancemap#'+j.card+'">Full record and citations</a></div></div>';
  }
  var subs='';
  if(!isSub && j.subs && SUBS[j.subs]){
    subs='<div class="subs"><span class="lab">Sub-national rules'+(j.subs==='usa'?' · all 50 states + DC':'')+'</span>'+SUBS[j.subs].slice().sort(function(a,b){return a.name<b.name?-1:1}).map(function(s){ return '<button type="button" class="sub" data-sub="'+j.subs+'" data-id="'+s.id+'"><span><span class="chip" style="--dot:'+cssv(VIEWS.gate.vars[s.gate])+'">'+esc(LABELS.gate[s.gate])+'</span> <span class="nm">'+esc(s.name)+'</span></span><span class="fc mono">FC ≥'+s.fcMin+'</span></button>'; }).join('')+'</div>';
  }
  P.innerHTML=head+rows+subs;
  P.querySelector('.close').addEventListener('click',closeRecord);
  P.querySelectorAll('.sub').forEach(function(b){ b.addEventListener('click',function(){
    var s=SUBS[b.dataset.sub].filter(function(x){return x.id===b.dataset.id})[0];
    if(b.dataset.sub==='usa'){ setLevel('usa'); select(s.id); }
    else { renderSubPanel(j,s); }
  })});
  openDrawer();
}
function renderSubPanel(parent,s){
  var P=$('panel');
  P.innerHTML='<div class="ph"><div class="title"><div><h3>'+esc(s.name)+'</h3><div class="region">'+esc(parent.name)+' · '+esc(s.ahj)+'</div></div><button class="close" type="button" aria-label="Close record">×</button></div><div class="chips">'+chip('gate',s.gate)+chip('cert',s.cert)+'</div></div><div class="rows"><div class="k">Water</div><div class="v"><span class="mono">FC ≥'+s.fcMin+' mg/L · pH '+esc(s.ph)+'</span></div><div class="k">Rule</div><div class="v">'+esc(s.t)+'</div>'+(s.trig?'<div class="k">Trigger</div><div class="v"><b>Conditional:</b> '+esc(s.trig)+'</div>':'')+'<div class="k path">Record</div><div class="v path"><a href="https://www.aquarevwater.us/compliancemap#'+s.card+'">Open the full record</a></div></div><div class="subs"><button type="button" class="sub" id="backbtn"><span class="nm">← Back to '+esc(parent.name)+'</span></button></div>';
  $('backbtn').addEventListener('click',renderPanel);
  P.querySelector('.close').addEventListener('click',closeRecord);
  openDrawer();
}
function closeRecord(){ state.sel=null; markSelected(); renderPanel(); }
function select(id){
  state.sel = (state.sel===id && state.level!=='usa') ? null : id;
  markSelected(); renderPanel();
  if(state.sel) ensureVisible(state.sel);
}

/* ===================== SEARCH ===================== */
var resIdx=-1;
function searchPool(){
  var q=state.q.toLowerCase(); if(!q) return [];
  var out=[];
  if(state.level==='usa'){ SUBS.usa.forEach(function(s){ if(matches(s,q)) out.push({kind:'state',j:s}); }); }
  else {
    J.forEach(function(j){ if(matches(j,q)) out.push({kind:'world',j:j}); });
    SUBS.usa.forEach(function(s){ if(matches(s,q)) out.push({kind:'state',j:s}); });
  }
  return out.slice(0,8);
}
function renderResults(){
  var R=$('results'), inp=$('q'); var list=searchPool();
  if(!state.q){ R.classList.remove('open'); R.innerHTML=''; inp.setAttribute('aria-expanded','false'); resIdx=-1; return; }
  if(!list.length){ R.innerHTML='<div class="res none">No match. Try a country, US state or agency name.</div>'; }
  else {
    R.innerHTML=list.map(function(r,i){ var j=r.j; var key=rawKey(j); var v=VIEWS[state.view]; return '<button type="button" class="res'+(i===resIdx?' active':'')+'" data-i="'+i+'"><span class="rn">'+esc(j.name)+'</span><span class="rr">'+esc(r.kind==='state'?'United States · state':j.region)+'</span><span class="chip" style="--dot:'+cssv(v.vars[key])+'">'+esc(labelOf(key))+'</span></button>'; }).join('');
    R.querySelectorAll('.res').forEach(function(b){ b.addEventListener('mousedown',function(e){ e.preventDefault(); pickResult(list[+b.dataset.i]); }); });
  }
  R.classList.add('open'); inp.setAttribute('aria-expanded','true');
}
function pickResult(r){
  if(!r) return;
  state.q=''; $('q').value=''; renderResults();
  if(r.kind==='state'){ if(state.level!=='usa') setLevel('usa'); select(r.j.id); }
  else { if(state.level!=='world') setLevel('world'); select(r.j.id); }
  markSelected();
}
(function(){
  var inp=$('q');
  inp.addEventListener('input',function(){ state.q=inp.value.trim(); resIdx=-1; renderResults(); markSelected(); if(state.level==='list') renderTable(); });
  inp.addEventListener('keydown',function(e){
    var list=searchPool();
    if(e.key==='ArrowDown'){ e.preventDefault(); resIdx=Math.min(list.length-1,resIdx+1); renderResults(); }
    else if(e.key==='ArrowUp'){ e.preventDefault(); resIdx=Math.max(0,resIdx-1); renderResults(); }
    else if(e.key==='Enter'){ e.preventDefault(); pickResult(list[resIdx<0?0:resIdx]); }
    else if(e.key==='Escape'){ state.q=''; inp.value=''; renderResults(); markSelected(); inp.blur(); }
  });
  inp.addEventListener('focus',function(){ if(state.q) renderResults(); });
  document.addEventListener('click',function(e){ if(!e.target.closest('.search')){ $('results').classList.remove('open'); inp.setAttribute('aria-expanded','false'); } });
})();

/* ===================== TABLE ===================== */
var sortKey='name', sortDir=1;
function renderTable(){
  var tb=document.querySelector('#tbl tbody');
  var rows=J.filter(function(j){return !isDim(j)}).slice().sort(function(a,b){ var x=a[sortKey],y=b[sortKey]; var xn=(x==null||x==='—'), yn=(y==null||y==='—'); if(xn&&yn) return 0; if(xn) return 1; if(yn) return -1; return (x>y?1:x<y?-1:0)*sortDir; });
  tb.innerHTML=rows.map(function(j){ return '<tr><td class="n" data-id="'+j.id+'">'+esc(j.name)+'</td><td>'+esc(j.region)+'</td><td><span class="dot" style="background:'+cssv(VIEWS.gate.vars[j.gate])+'"></span>'+esc(LABELS.gate[j.gate])+'</td><td><span class="dot" style="background:'+cssv(VIEWS.cert.vars[j.cert])+'"></span>'+esc(LABELS.cert[j.cert])+'</td><td><span class="dot" style="background:'+cssv(VIEWS.process.vars[j.process])+'"></span>'+esc(LABELS.process[j.process])+'</td><td style="max-width:260px">'+(j.trig?'<b>Conditional:</b> '+esc(j.trig):'—')+'</td><td class="mono">'+esc(fmtFC(j))+'</td><td class="mono">'+esc(j.ph)+'</td><td><span class="dot" style="background:'+cssv(VIEWS.conf.vars[j.conf])+'"></span>'+esc(LABELS.conf[j.conf])+'</td></tr>'; }).join('');
  tb.querySelectorAll('td.n').forEach(function(td){ td.addEventListener('click',function(){ state.sel=td.dataset.id; renderPanel(); }); });
  var lc=$('listcount'); if(lc){ lc.textContent = (rows.length===J.length) ? J.length+' jurisdictions' : rows.length+' of '+J.length+' jurisdictions shown'+(state.filter?' · filtered by "'+labelOf(state.filter)+'"':'')+(state.q?' · search "'+state.q+'"':''); }
}
document.querySelectorAll('#tbl th').forEach(function(th){ th.addEventListener('click',function(){ var k=th.dataset.s; if(sortKey===k) sortDir*=-1; else {sortKey=k; sortDir=1;} renderTable(); }); });

/* ===================== LEVEL / FOCUS / CONTROLS ===================== */
function setLevel(l){
  state.level=l; state.filter=null;
  document.querySelectorAll('[aria-label="Map level"] button').forEach(function(b){ b.setAttribute('aria-pressed', b.dataset.level===l?'true':'false'); });
  $('mapcard').classList.toggle('hidden', l==='list');
  $('listcard').classList.toggle('hidden', l!=='list');
  $('focuswrap').style.visibility = l==='world' ? 'visible' : 'hidden';
  if(l==='list'){ renderLegend(); renderTable(); }
  else { state.sel = (l==='usa' && !USAB[state.sel]) ? null : (l==='world' && USAB[state.sel] ? 'USA' : state.sel); buildMap(); renderLegend(); }
  renderPanel();
}
document.querySelectorAll('#qtabs .qtab').forEach(function(b){ b.addEventListener('click',function(){ setView(b.dataset.view); }); });
document.querySelectorAll('[aria-label="Map level"] button').forEach(function(b){ b.addEventListener('click',function(){ setLevel(b.dataset.level); }); });
$('focus').addEventListener('change',function(){ state.region=this.value; if(state.level==='world') focusRegion(state.region,true); });
$('zin').addEventListener('click',function(){zoomBy(1.6)});
$('zout').addEventListener('click',function(){zoomBy(1/1.6)});
$('zreset').addEventListener('click',function(){ state.region='world'; $('focus').value='world'; tk={k:1,x:0,y:0}; applyT(true); });
(function(){
  var btn=$('helpbtn'), box=$('help');
  function setHelp(open){ box.hidden=!open; btn.setAttribute('aria-expanded', open?'true':'false'); }
  btn.addEventListener('click',function(e){ e.stopPropagation(); setHelp(box.hidden); });
  document.addEventListener('click',function(e){ if(!box.hidden && !box.contains(e.target)) setHelp(false); });
  document.addEventListener('keydown',function(e){ if(e.key==='Escape'){ setHelp(false); if(state.sel && document.activeElement!==$('q')){ closeRecord(); } } });
})();
var rt; window.addEventListener('resize',function(){ clearTimeout(rt); rt=setTimeout(function(){ if(state.level!=='list'){ buildMap(); } },200); });
var mq=window.matchMedia('(prefers-color-scheme: dark)'); if(mq.addEventListener) mq.addEventListener('change',function(){ if(state.level!=='list') buildMap(); renderLegend(); renderPanel(); });
new MutationObserver(function(){ if(state.level!=='list') buildMap(); renderLegend(); renderPanel(); }).observe(document.documentElement,{attributes:true,attributeFilter:['data-theme']});

/* ===================== BOOT ===================== */
(function boot(){
  if(typeof Datamap==='undefined'){ $('map').innerHTML='<p style="padding:24px;color:var(--ink-2)">The map library did not load. The table view still works.</p>'; setLevel('list'); return; }
  buildMap(); renderLegend(); renderPanel();
})();
})();
